// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class AnexoConfiguration : IEntityTypeConfiguration<Anexo>
    {
        public void Configure(EntityTypeBuilder<Anexo> entity)
        {
            entity.ToTable("ANEXO", "dbo");

            entity.Property(e => e.Arquivo).IsRequired();

            entity.Property(e => e.MimeType).IsRequired();

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.TipoDocumentoAnexo)
                .WithMany(p => p.Anexo)
                .HasForeignKey(d => d.TipoDocumentoAnexoId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Anexo> entity);
    }
}
