// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class IdxDataHoraConfiguration : IEntityTypeConfiguration<IdxDataHora>
    {
        public void Configure(EntityTypeBuilder<IdxDataHora> entity)
        {
            entity.HasKey(e => e.DataHora)
                .HasName("PK__IDX_Data_Hora__6CA31EA0");

            entity.ToTable("IDX_Data_Hora", "dbo");

            entity.HasIndex(e => e.Data, "IDX_DATA");

            entity.HasIndex(e => e.Hora, "IDX_HORA");

            entity.Property(e => e.DataHora).HasColumnName("DATA_HORA");

            entity.Property(e => e.Data).HasColumnName("DATA");

            entity.Property(e => e.Hora).HasColumnName("HORA");

            entity.Property(e => e.Objetos)
                .HasColumnType("text")
                .HasColumnName("OBJETOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<IdxDataHora> entity);
    }
}
