// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class IdxFlutuantesConfiguration : IEntityTypeConfiguration<IdxFlutuantes>
    {
        public void Configure(EntityTypeBuilder<IdxFlutuantes> entity)
        {
            entity.HasKey(e => e.Numero)
                .HasName("PK__IDX_Flutuantes__6ABAD62E");

            entity.ToTable("IDX_Flutuantes", "dbo");

            entity.Property(e => e.Numero).HasColumnName("NUMERO");

            entity.Property(e => e.Objetos)
                .HasColumnType("text")
                .HasColumnName("OBJETOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<IdxFlutuantes> entity);
    }
}
