// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class IdxInteirosConfiguration : IEntityTypeConfiguration<IdxInteiros>
    {
        public void Configure(EntityTypeBuilder<IdxInteiros> entity)
        {
            entity.HasKey(e => new { e.NumeroUnsigned, e.NumeroSigned })
                .HasName("PK__IDX_Inteiros__68D28DBC");

            entity.ToTable("IDX_Inteiros", "dbo");

            entity.Property(e => e.NumeroUnsigned).HasColumnName("NUMERO_UNSIGNED");

            entity.Property(e => e.NumeroSigned).HasColumnName("NUMERO_SIGNED");

            entity.Property(e => e.Objetos)
                .HasColumnType("text")
                .HasColumnName("OBJETOS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<IdxInteiros> entity);
    }
}
