// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbAnexoConfiguration : IEntityTypeConfiguration<TbAnexo>
    {
        public void Configure(EntityTypeBuilder<TbAnexo> entity)
        {
            entity.HasKey(e => e.CdAnexo);

            entity.ToTable("tb_anexo", "dbo");

            entity.HasComment("Registrava o recebimento de anexos dos laudos na seção de protocolo, Não é mais utilizada.	");

            entity.Property(e => e.CdAnexo)
                .HasColumnName("cd_anexo")
                .HasComment("Chave primaria. Código do anexo que será recebido na seção de protocolo.");

            entity.Property(e => e.CdArquivador)
                .HasColumnName("cd_arquivador")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que arquivou o anexo.");

            entity.Property(e => e.CdHomologador)
                .HasColumnName("cd_homologador")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que homologou o anexo.");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do documento (laudo, relatório ou SVO)");

            entity.Property(e => e.DtArquivado)
                .HasColumnType("datetime")
                .HasColumnName("dt_arquivado")
                .HasComment("Data do arquivamento do anexo");

            entity.Property(e => e.DtHomologado)
                .HasColumnType("datetime")
                .HasColumnName("dt_homologado")
                .HasComment("Data da homologação do anexo.");

            entity.Property(e => e.HrArquivado)
                .HasColumnType("datetime")
                .HasColumnName("hr_arquivado")
                .HasComment("Hora do arquivamento do anexo.");

            entity.Property(e => e.HrHomologado)
                .HasColumnType("datetime")
                .HasColumnName("hr_homologado")
                .HasComment("Hora da homologação do anexo");

            entity.Property(e => e.NrFolhas)
                .HasColumnName("nr_folhas")
                .HasComment("Quantidade de folhas contidas no anexo que será recebido pela seção de protocolo.");

            entity.Property(e => e.Obs)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("obs")
                .HasComment("Informações adicionais (observações) sobre o anexo.");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbAnexo> entity);
    }
}
