// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbCartorioConfiguration : IEntityTypeConfiguration<TbCartorio>
    {
        public void Configure(EntityTypeBuilder<TbCartorio> entity)
        {
            entity.HasKey(e => e.CdCartorio);

            entity.ToTable("tb_cartorio", "dbo");

            entity.HasComment("Tabela de cartórios onde são registradas as certidões de óbito para retirada de corpos");

            entity.Property(e => e.CdCartorio)
                .HasColumnName("cd_cartorio")
                .HasComment("Chave primaria autoincremental. Código do cartório");

            entity.Property(e => e.Endereco)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("endereco")
                .HasComment("Endereço do cartório");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.NmCartorio)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_cartorio")
                .HasComment("Nome do cartório");

            entity.Property(e => e.Telefone)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("telefone")
                .HasComment("Número do telefone do cartório");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbCartorio> entity);
    }
}
