// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbChamadoOsConfiguration : IEntityTypeConfiguration<TbChamadoOs>
    {
        public void Configure(EntityTypeBuilder<TbChamadoOs> entity)
        {
            entity.HasKey(e => e.CdChamado);

            entity.ToTable("tb_chamado_os", "dbo");

            entity.HasComment("Chamados técnicos feitos pela seção de material e transporte do IML junto a diversas empresas prestadoras de serviço para a PCDF");

            entity.Property(e => e.CdChamado)
                .HasColumnName("cd_chamado")
                .HasComment("Chave primaria autoincremental. Código do registro do chamado técnico");

            entity.Property(e => e.CdExcluidor)
                .HasColumnName("cd_excluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário excluidor do registro de chamado");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrageira na tabela tb_usuario. Código do usuário incluidor do registro do chamado");

            entity.Property(e => e.DtChamado)
                .HasColumnType("datetime")
                .HasColumnName("dt_chamado")
                .HasComment("Data da abertura do chamado junto á empresa prestadora de serviços");

            entity.Property(e => e.DtExclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_exclusao")
                .HasComment("Data da exclusão do registro do chamado");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do registro do chamado técnico junto a empresas prestadoras de serviço");

            entity.Property(e => e.DtTermino)
                .HasColumnType("datetime")
                .HasColumnName("dt_termino")
                .HasComment("Data do encerramento do chamado pela empresa prestadora do serviço");

            entity.Property(e => e.Historico)
                .HasMaxLength(600)
                .IsUnicode(false)
                .HasColumnName("historico")
                .HasComment("Descrição do problema e dos acontecimentos durante a vigência do chamado");

            entity.Property(e => e.NmEmpresa)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("nm_empresa")
                .HasComment("Nome da empresa prestadora do serviço");

            entity.Property(e => e.NmExterno)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("nm_externo")
                .HasComment("Nome do funcionário que recebeu o chamado na empresa prestadora do serviço");

            entity.Property(e => e.NmIml)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("nm_iml")
                .HasComment("Nome do servidor do IML que fez a abertura do chamado na empresa que prrestará o serviço");

            entity.Property(e => e.NrChamado)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("nr_chamado")
                .HasComment("Número do chamado registrado na empresa prestadora de serviço");

            entity.Property(e => e.Patrimonio)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("patrimonio")
                .HasComment("Número do patrimônio do bem objeto da abertura do chamado");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbChamadoOs> entity);
    }
}
