// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbCidadeConfiguration : IEntityTypeConfiguration<TbCidade>
    {
        public void Configure(EntityTypeBuilder<TbCidade> entity)
        {
            entity.HasKey(e => e.CdCidade);

            entity.ToTable("tb_cidade", "dbo");

            entity.HasComment("Tabela básica de cidades. Cadastro de cidades");

            entity.Property(e => e.CdCidade)
                .HasColumnName("cd_cidade")
                .HasComment("Chave primaria autoincremental. Código da cidade");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.Incluidor)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu a cidade");

            entity.Property(e => e.NmCidade)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_cidade")
                .HasComment("Nome da cidade");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbCidade> entity);
    }
}
