// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbConselhoConfiguration : IEntityTypeConfiguration<TbConselho>
    {
        public void Configure(EntityTypeBuilder<TbConselho> entity)
        {
            entity.HasKey(e => e.CdConselho);

            entity.ToTable("tb_conselho", "dbo");

            entity.HasComment("Conselhos de classe aos quais pertencem os legistas que fazem laudos ou usuários que fazem relatórios no SICOLA");

            entity.Property(e => e.CdConselho)
                .HasColumnName("cd_conselho")
                .HasComment("Chave primaria autoincremental. Código do conselho de classe trabalhista");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.NmConselho)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_conselho")
                .HasComment("Nome do conselho de classe");

            entity.Property(e => e.SiglaConselho)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("sigla_conselho")
                .HasComment("Sigla do conselho de classe");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbConselho> entity);
    }
}
