// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbDaPendenteConfiguration : IEntityTypeConfiguration<TbDaPendente>
    {
        public void Configure(EntityTypeBuilder<TbDaPendente> entity)
        {
            entity.HasKey(e => e.CdUsuario);

            entity.ToTable("tb_da_pendente", "dbo");

            entity.HasComment("Usuários que não preencheram o cadastro com dados pessoais básicos.");

            entity.Property(e => e.CdUsuario)
                .ValueGeneratedNever()
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que ainda não preencheu o cadastro com dados pessoais");

            entity.Property(e => e.Tempo)
                .HasColumnName("tempo")
                .HasComment("Tempo em dias que está pendente");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbDaPendente> entity);
    }
}
