// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbDocsFilaConfiguration : IEntityTypeConfiguration<TbDocsFila>
    {
        public void Configure(EntityTypeBuilder<TbDocsFila> entity)
        {
            entity.HasKey(e => e.CdUsuario);

            entity.ToTable("tb_docs_fila", "dbo");

            entity.HasComment("Servidores do IML que formam a fila para recebimento de documentos encaminhados pela SAPE, normalmente são os legistas. Aparentemente este recurso do SICOLA nunca foi utilizado.");

            entity.Property(e => e.CdUsuario)
                .ValueGeneratedNever()
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que está na fila");

            entity.Property(e => e.Ordem)
                .HasColumnName("ordem")
                .HasComment("Número de ordem do usuário na fila de recebimento de documentos. É este número que classifica a lista.");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbDocsFila> entity);
    }
}
