// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbEstadoCivilConfiguration : IEntityTypeConfiguration<TbEstadoCivil>
    {
        public void Configure(EntityTypeBuilder<TbEstadoCivil> entity)
        {
            entity.HasKey(e => e.CdEstadoCivil);

            entity.ToTable("tb_estado_civil", "dbo");

            entity.HasComment("Estado civil do periciando do laudo");

            entity.Property(e => e.CdEstadoCivil)
                .HasColumnName("cd_estado_civil")
                .HasComment("Chave primaria autoincremental. Código do estado civil do periciando do laudo");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro do estado civil foi excluído");

            entity.Property(e => e.NmEstadoCivil)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("nm_estado_civil")
                .HasComment("Nome do estado civil do periciando");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbEstadoCivil> entity);
    }
}
