// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbEtiquetaRuimConfiguration : IEntityTypeConfiguration<TbEtiquetaRuim>
    {
        public void Configure(EntityTypeBuilder<TbEtiquetaRuim> entity)
        {
            entity.HasKey(e => e.CdEtiqueta);

            entity.ToTable("tb_etiqueta_ruim", "dbo");

            entity.HasComment("Etiquetas da Central de Guarda e Custódia de Vestígio que foram danificadas dentro do IML");

            entity.Property(e => e.CdEtiqueta)
                .HasColumnName("cd_etiqueta")
                .HasComment("Chave primaria autoincremental. Código do registro da etiqueta danificada");

            entity.Property(e => e.CdExcluidor)
                .HasColumnName("cd_excluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que exclui o registro da etiqueta danificada");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que fez o registro da etiqueta danificada");

            entity.Property(e => e.CdMotivo)
                .HasColumnName("cd_motivo")
                .HasComment("Chave estrangeira na tabela tb_motivo_etiqueta. Código do motivo do dano na etiqueta");

            entity.Property(e => e.DtExclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_exclusao")
                .HasComment("Data da exclusão do registro da etiqueta danificada");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data do registro da etiqueta danificada");

            entity.Property(e => e.Numero)
                .HasColumnName("numero")
                .HasComment("Número da etiqueta danificada no IML");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbEtiquetaRuim> entity);
    }
}
