// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbFotoEntregueConfiguration : IEntityTypeConfiguration<TbFotoEntregue>
    {
        public void Configure(EntityTypeBuilder<TbFotoEntregue> entity)
        {
            entity.HasKey(e => e.CdFotoEntregue);

            entity.ToTable("tb_foto_entregue", "dbo");

            entity.HasComment("Recibo de fotos impressas e entregues ao legista. Deixou de ser usado em 23/04/2014 pois as fotos passaram a ser em arquivo digital.");

            entity.Property(e => e.CdFotoEntregue)
                .HasColumnName("cd_foto_entregue")
                .HasComment("Chave primaria autoincremental. Código do registro da foto entregue ao legista");

            entity.Property(e => e.CdFotografo)
                .HasColumnName("cd_fotografo")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do servidor responsável pelas fotografias");

            entity.Property(e => e.CdIncluiu)
                .HasColumnName("cd_incluiu")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que fez o registro da foto entregue ao legista");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo vinculado à fotografia entregue ao legista");

            entity.Property(e => e.DtEntrega)
                .HasColumnType("datetime")
                .HasColumnName("dt_entrega")
                .HasComment("Data da entrega das fotografias impressas ao legista");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data do registro da foto entregue ao legista");

            entity.Property(e => e.Obs)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("obs")
                .HasComment("Informações adicionais sobre a foto entregue ao legista");

            entity.Property(e => e.Qtde)
                .HasColumnName("qtde")
                .HasComment("Quantidade de fotografias entregues ao legista");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbFotoEntregue> entity);
    }
}
