// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbFotoImprimirConfiguration : IEntityTypeConfiguration<TbFotoImprimir>
    {
        public void Configure(EntityTypeBuilder<TbFotoImprimir> entity)
        {
            entity.HasKey(e => new { e.CdLaudo, e.CdPerito1 });

            entity.ToTable("tb_foto_imprimir", "dbo");

            entity.HasComment("Fotografias destinadas à revelação e impressão no laboratório fotográfico. Deixou de ser utilizado quando as fotos passaram a ser digitais.");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo ao qual está vinculada a fotografia a ser impressa");

            entity.Property(e => e.CdPerito1)
                .HasColumnName("cd_perito1")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do legista que solicitou a revelação e impressão da fotografia");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbFotoImprimir> entity);
    }
}
