// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbFunerariaConfiguration : IEntityTypeConfiguration<TbFuneraria>
    {
        public void Configure(EntityTypeBuilder<TbFuneraria> entity)
        {
            entity.HasKey(e => e.CdFuneraria);

            entity.ToTable("tb_funeraria", "dbo");

            entity.HasComment("Cadastro de funerárias autorizadas a fazer o traslado de corpos do IML");

            entity.Property(e => e.CdFuneraria)
                .HasColumnName("cd_funeraria")
                .HasComment("Chave primaria autoincremental. Código do registro da funerária autorizada a fazer traslado");

            entity.Property(e => e.Ativo)
                .HasColumnName("ativo")
                .HasComment("Informa se a funerária está ativa (autorizada) ou não.");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro da funerária");

            entity.Property(e => e.Cnpj)
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("cnpj")
                .HasComment("CNPJ da funerária");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do registro da funerária");

            entity.Property(e => e.Endereco)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("endereco")
                .HasComment("Endereço da funerária");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.NmFuneraria)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_funeraria")
                .HasComment("Razão social da funerária");

            entity.Property(e => e.Obs)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("obs")
                .HasComment("Informações adicionais sobre a funerária");

            entity.Property(e => e.Socios)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("socios")
                .HasComment("Nome dos sócios da empresa funerária");

            entity.Property(e => e.Telefone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("telefone")
                .HasComment("Número do telefone da funerária");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbFuneraria> entity);
    }
}
