// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbIgnoradoFichaConfiguration : IEntityTypeConfiguration<TbIgnoradoFicha>
    {
        public void Configure(EntityTypeBuilder<TbIgnoradoFicha> entity)
        {
            entity.HasKey(e => e.CdIgnoradoFicha);

            entity.ToTable("tb_ignorado_ficha", "dbo");

            entity.HasComment("Ficha com características do cadáver classificado como ignorado (sem identificação) pela seção de necrópsia");

            entity.Property(e => e.CdIgnoradoFicha)
                .HasColumnName("cd_ignorado_ficha")
                .HasComment("Chave primaria autoincremental. Código do registro da ficha com dados do cadáver ignorado");

            entity.Property(e => e.Adereco)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("adereco")
                .HasComment("Descrição dos adereços encontrados com o cadáver");

            entity.Property(e => e.Assimetria)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("assimetria")
                .HasComment("Descrição de características assimétricas do cadáver");

            entity.Property(e => e.CdCorCabelo)
                .HasColumnName("cd_cor_cabelo")
                .HasComment("Chave estrangeira na tabela tb_cor_cabelo. Código da cor do cabelo do cadáver");

            entity.Property(e => e.CdCorPele)
                .HasColumnName("cd_cor_pele")
                .HasComment("Chave estrangeira na tabela tb_cor_pele. Código da cor da pele do cadáver");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu a ficha");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo cadavérico ao qual pertence a ficha");

            entity.Property(e => e.CdSexo)
                .HasColumnName("cd_sexo")
                .HasComment("Chave estrangeira na tabela tb_sexo. Código do sexo do cadáver");

            entity.Property(e => e.CdTpCabelo)
                .HasColumnName("cd_tp_cabelo")
                .HasComment("Chave estrangeira na tabela tb_cor_cabelo. Código do tipo do cabelo do cadáver");

            entity.Property(e => e.Cicatriz)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("cicatriz")
                .HasComment("Descrição de cicatrizes encontradas no cadáver");

            entity.Property(e => e.Cirurgia)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("cirurgia")
                .HasComment("Descrição de cirurgias encontradas no cadáver");

            entity.Property(e => e.Dente)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("dente")
                .HasComment("Informações sobre a dentição do cadáver");

            entity.Property(e => e.DtIncluiu)
                .HasColumnType("datetime")
                .HasColumnName("dt_incluiu")
                .HasComment("Data da inclusão da ficha de cadáver ignorado");

            entity.Property(e => e.DtLocalizado)
                .HasColumnType("datetime")
                .HasColumnName("dt_localizado")
                .HasComment("Data da localização do cadáver");

            entity.Property(e => e.DtMorte)
                .HasColumnType("datetime")
                .HasColumnName("dt_morte")
                .HasComment("Data aproximada da morte");

            entity.Property(e => e.Esmalte)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("esmalte")
                .HasComment("Descrição sobre esmalte nas unhas do cadáver");

            entity.Property(e => e.Estatura)
                .HasColumnName("estatura")
                .HasComment("Estatura do cadáver em cm");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.Fratura)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("fratura")
                .HasComment("Descrição de fraturas encontradas no cadáver");

            entity.Property(e => e.Idade)
                .HasColumnName("idade")
                .HasComment("Idade aproximada do cadáver em anos");

            entity.Property(e => e.Identificado)
                .HasColumnName("identificado")
                .HasComment("Informa se o cadáver foi identificado");

            entity.Property(e => e.Local)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("local")
                .HasComment("Local onde o cadáver foi localizado");

            entity.Property(e => e.NrCalcado)
                .HasColumnName("nr_calcado")
                .HasComment("Número do calçado utilizado pelo cadáver");

            entity.Property(e => e.Obs)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("obs")
                .HasComment("Informações adicionais sobre o cadáver");

            entity.Property(e => e.Peso)
                .HasColumnName("peso")
                .HasComment("Peso do cadáver em kg");

            entity.Property(e => e.Protese)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("protese")
                .HasComment("Descrição sobre próteses encontradas no cadáver");

            entity.Property(e => e.Sinal)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("sinal")
                .HasComment("Descrição de sinais naturais do cadáver");

            entity.Property(e => e.Tatuagem)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("tatuagem")
                .HasComment("Descrição das tatuagens encontradas no cadáver");

            entity.Property(e => e.Veste)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("veste")
                .HasComment("Descrição das vestes encontradas com o cadáver");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbIgnoradoFicha> entity);
    }
}
