// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLaudoPeConfiguration : IEntityTypeConfiguration<TbLaudoPe>
    {
        public void Configure(EntityTypeBuilder<TbLaudoPe> entity)
        {
            entity.HasKey(e => e.CdLaudoPe);

            entity.ToTable("tb_laudo_pe", "dbo");

            entity.HasComment("Laudos que foram feitos através de deslocamento externo ao IML pelo legista");

            entity.Property(e => e.CdLaudoPe)
                .HasColumnName("cd_laudo_pe")
                .HasComment("Chave primaria autoincremental. Código do registro de um laudo feito fora do IML");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que informou que o laudo foi feito fora do IML");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo que foi feito fora do IML");

            entity.Property(e => e.CdUsuario)
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do perito do laudo que foi feito fora do IML");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data do registro da informação de que o laudo foi feito fora do IML");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.Local)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("local")
                .HasComment("Local externo ao IML onde foi feita a perícia do laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLaudoPe> entity);
    }
}
