// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLaudoIiConfiguration : IEntityTypeConfiguration<TbLaudoIi>
    {
        public void Configure(EntityTypeBuilder<TbLaudoIi> entity)
        {
            entity.HasKey(e => e.CdLaudoIi);

            entity.ToTable("tb_laudo_ii", "dbo");

            entity.HasComment("Pedidos de identificação de cadáver feito ao papiloscopista do ii");

            entity.Property(e => e.CdLaudoIi)
                .HasColumnName("cd_laudo_ii")
                .HasComment("Chave primaria autoincremental. Código do registro do pedido de identificação por papiloscopia");

            entity.Property(e => e.AnoLaudoIi)
                .HasColumnName("ano_laudo_ii")
                .HasComment("Ano do documento do instituto de identificação que confirmou a identidade do cadáver");

            entity.Property(e => e.CadaverLiberado)
                .HasColumnName("cadaver_liberado")
                .HasComment("Informa se o cadáver está liberado para entrega à funerária");

            entity.Property(e => e.Cancelado)
                .HasColumnName("cancelado")
                .HasComment("Informa se o pedido de identificação papiloscópica foi cancelado");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que solicitou a identificação papiloscópica");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo cadavérico cujo cadáver deverá ser identificado pelas digitais");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da solicitação da identificação pela impressão digital");

            entity.Property(e => e.Liberador)
                .HasColumnName("liberador")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que liberou o cadáver para a entrega à funerária");

            entity.Property(e => e.NrLaudoIi)
                .HasColumnName("nr_laudo_ii")
                .HasComment("Número do documento do instituto de identificação que confirmou a identidade do cadáver");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLaudoIi> entity);
    }
}
