// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLogVisualizaJustificaConfiguration : IEntityTypeConfiguration<TbLogVisualizaJustifica>
    {
        public void Configure(EntityTypeBuilder<TbLogVisualizaJustifica> entity)
        {
            entity.HasKey(e => e.CdLogVisualizaJustifica);

            entity.ToTable("tb_log_visualiza_justifica", "dbo");

            entity.HasComment("Justificativa de usuários externos para visualizar laudos. Deixou de ser usado em 21/09/2009");

            entity.Property(e => e.CdLogVisualizaJustifica)
                .HasColumnName("cd_log_visualiza_justifica")
                .HasComment("Chave primaria autoincremental. Código do registro da justificativa feita por um usuário para ver um laudo");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo cujo usuário justificou a sua visualização");

            entity.Property(e => e.CdUsuario)
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que justificou a visualização de um laudo");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da justificativa de visualização de um laudo");

            entity.Property(e => e.Justificativa)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("justificativa")
                .HasComment("Justificativa para visualizar um laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLogVisualizaJustifica> entity);
    }
}
