// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLogGraficoConfiguration : IEntityTypeConfiguration<TbLogGrafico>
    {
        public void Configure(EntityTypeBuilder<TbLogGrafico> entity)
        {
            entity.HasKey(e => e.CdLogGrafico);

            entity.ToTable("tb_log_grafico", "dbo");

            entity.HasComment("Registro de visualização de gráficos (JPG) dos gráficos por usuários do SICOLA");

            entity.Property(e => e.CdLogGrafico)
                .HasColumnName("cd_log_grafico")
                .HasComment("Chave primaria autoincremental. Código do registro da visualização de um gráfico pelo usuário");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo ao qual pertence o gráfico visualizado");

            entity.Property(e => e.CdUsuario)
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que visualizou o gráfico");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da visualização do gráfico pelo usuário");

            entity.Property(e => e.Ip)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("ip")
                .HasComment("Identificação do computador utilizado para visualizar o gráfico");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLogGrafico> entity);
    }
}
