// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLogLaboratorioConfiguration : IEntityTypeConfiguration<TbLogLaboratorio>
    {
        public void Configure(EntityTypeBuilder<TbLogLaboratorio> entity)
        {
            entity.HasKey(e => e.CdLogLaboratorio);

            entity.ToTable("tb_log_laboratorio", "dbo");

            entity.HasComment("Registro de atividades nos exames laboratoriais");

            entity.Property(e => e.CdLogLaboratorio)
                .HasColumnName("cd_log_laboratorio")
                .HasComment("Chave primaria autoincremental. Código do registro de uma alteração no exame laboratorial");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo ao qual pertence o pedido de exame laboratorial");

            entity.Property(e => e.CdToxicologico)
                .HasColumnName("cd_toxicologico")
                .HasComment("Chave estrangeira na tabela tb_toxicologico. Código do pedido de exame laboratorial que foi alterado");

            entity.Property(e => e.DtLog)
                .HasColumnType("datetime")
                .HasColumnName("dt_log")
                .HasComment("Data da alteração no exame laboratorial");

            entity.Property(e => e.Loglog)
                .HasMaxLength(2800)
                .IsUnicode(false)
                .HasColumnName("loglog")
                .HasComment("Descrição da alteração realizada no exame laboratorial");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLogLaboratorio> entity);
    }
}
