// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLogFotoExcluidaConfiguration : IEntityTypeConfiguration<TbLogFotoExcluida>
    {
        public void Configure(EntityTypeBuilder<TbLogFotoExcluida> entity)
        {
            entity.HasKey(e => e.CdLogFotoExcluida);

            entity.ToTable("tb_log_foto_excluida", "dbo");

            entity.HasComment("Registro das exclusões de fotos dos laudos");

            entity.Property(e => e.CdLogFotoExcluida)
                .HasColumnName("cd_log_foto_excluida")
                .HasComment("Chave primaria autoincremental. Código do registro da exclusão de uma foto de um laudo");

            entity.Property(e => e.CdExcluidor)
                .HasColumnName("cd_excluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu a foto do laudo");

            entity.Property(e => e.CdFoto)
                .HasColumnName("cd_foto")
                .HasComment("Chave estrangeira na tabela tb_foto. Código da foto que foi excluída");

            entity.Property(e => e.DtExclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_exclusao")
                .HasComment("Data da exclusão da foto do laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLogFotoExcluida> entity);
    }
}
