// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLogImagemConfiguration : IEntityTypeConfiguration<TbLogImagem>
    {
        public void Configure(EntityTypeBuilder<TbLogImagem> entity)
        {
            entity.HasKey(e => e.CdLogImagem);

            entity.ToTable("tb_log_imagem", "dbo");

            entity.HasComment("Usuários que visualizaram apenas as fotos do laudo");

            entity.Property(e => e.CdLogImagem)
                .HasColumnName("cd_log_imagem")
                .HasComment("Chave primaria autoincremental. Código do registro da visualização de imagens do laudo por um usuário");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo que contém as imagens visualizadas");

            entity.Property(e => e.CdUsuario)
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que visualizou imagens do laudo");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da visualização das imagens do laudo pelo usuário");

            entity.Property(e => e.Ip)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("ip")
                .HasComment("Identificação do computador utilizado para visualizar as imagens do laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLogImagem> entity);
    }
}
