// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbLogNavegacaoConfiguration : IEntityTypeConfiguration<TbLogNavegacao>
    {
        public void Configure(EntityTypeBuilder<TbLogNavegacao> entity)
        {
            entity.HasKey(e => e.CdLogNavegacao);

            entity.ToTable("tb_log_navegacao", "dbo");

            entity.HasComment("Registro de atividades de navegação do usuário dentro do SICOLA");

            entity.Property(e => e.CdLogNavegacao)
                .HasColumnName("cd_log_navegacao")
                .HasComment("Chave primaria autoincremental. Código do registro da atividade de navegação feita pelo usuário");

            entity.Property(e => e.CdUsuario)
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que acessou a página");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data em que o usuário acessou a página");

            entity.Property(e => e.Ip)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("ip")
                .HasComment("Identificação do computador utilizado para acessar a página");

            entity.Property(e => e.Pagina)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("pagina")
                .HasComment("Página que foi acessada pelo usuário");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbLogNavegacao> entity);
    }
}
