// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbMateriaisConfiguration : IEntityTypeConfiguration<TbMateriais>
    {
        public void Configure(EntityTypeBuilder<TbMateriais> entity)
        {
            entity.HasKey(e => e.CodMaterial);

            entity.ToTable("tb_materiais", "dbo");

            entity.HasComment("Material de consumo utilizado no órgão");

            entity.Property(e => e.CodMaterial)
                .HasColumnName("Cod_Material")
                .HasComment("Chave primaria autoincremental. Código do registro do material de consumo");

            entity.Property(e => e.CodOrgao)
                .HasColumnName("Cod_Orgao")
                .HasComment("Chave estrangeira na tabela tb_orgao. Código do órgão ao qual pertence o material de consumo");

            entity.Property(e => e.DescMaterial)
                .HasMaxLength(250)
                .HasColumnName("Desc_Material")
                .HasComment("Descrição do material de consumo utilizado no órgão");

            entity.Property(e => e.EstoqueAtual)
                .HasColumnName("Estoque_Atual")
                .HasComment("Quantidade atual do material em estoque no órgão");

            entity.Property(e => e.EstoqueMaximo)
                .HasColumnName("Estoque_Maximo")
                .HasComment("Quantidade máxima do material necessária em estoque");

            entity.Property(e => e.EstoqueMinimo)
                .HasColumnName("Estoque_Minimo")
                .HasComment("Quantidade mínima do material necessária em estoque");

            entity.Property(e => e.Excluido)
                .HasMaxLength(1)
                .HasComment("Informa se o material de consumo foi excluído");

            entity.Property(e => e.UnidadeMedida)
                .HasMaxLength(15)
                .HasColumnName("Unidade_Medida")
                .HasComment("Unidade de medida do material");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbMateriais> entity);
    }
}
