// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbModeloQuesitoConfiguration : IEntityTypeConfiguration<TbModeloQuesito>
    {
        public void Configure(EntityTypeBuilder<TbModeloQuesito> entity)
        {
            entity.HasKey(e => e.CdModeloQuesito);

            entity.ToTable("tb_modelo_quesito", "dbo");

            entity.HasComment("Modelos de resposta de quesitos para laudos mais comuns");

            entity.Property(e => e.CdModeloQuesito)
                .HasColumnName("cd_modelo_quesito")
                .HasComment("Chave primaria autoincremental. Código do registro do modelo de resposta de quesitos");

            entity.Property(e => e.CdQuesitoLaudo)
                .HasColumnName("cd_quesito_laudo")
                .HasComment("Chave estrangeira na tabela tb_quesito_laudo. Código do quesito de laudo que terá resposta padronizada no modelo");

            entity.Property(e => e.NmModelo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("nm_modelo")
                .HasComment("Nome descritivo do modelo de resposta de quesitos");

            entity.Property(e => e.TextoModelo)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("texto_modelo")
                .HasComment("Resposta padronizada do quesito para o modelo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbModeloQuesito> entity);
    }
}
