// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbObsResponsavelConfiguration : IEntityTypeConfiguration<TbObsResponsavel>
    {
        public void Configure(EntityTypeBuilder<TbObsResponsavel> entity)
        {
            entity.HasKey(e => e.CdObsResponsavel);

            entity.ToTable("tb_obs_responsavel", "dbo");

            entity.HasComment("Observações cadastradas para imprimir o termo de responsabilidade pelo cadáver");

            entity.Property(e => e.CdObsResponsavel)
                .HasColumnName("cd_obs_responsavel")
                .HasComment("Chave primaria autoincremental. Código do registro da observação do termo de responsabilidade");

            entity.Property(e => e.CdResponsavel)
                .HasColumnName("cd_responsavel")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu a observação");

            entity.Property(e => e.Obs)
                .HasColumnType("text")
                .HasColumnName("obs")
                .HasComment("Descrição da observação do termo de responsabilidade");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbObsResponsavel> entity);
    }
}
