// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbOrgaoLotacaoConfiguration : IEntityTypeConfiguration<TbOrgaoLotacao>
    {
        public void Configure(EntityTypeBuilder<TbOrgaoLotacao> entity)
        {
            entity.HasKey(e => e.CdOrgaoLotacao);

            entity.ToTable("tb_orgao_lotacao", "dbo");

            entity.HasComment("Órgãos de lotação dos usuários cadastrados no SICOLA");

            entity.Property(e => e.CdOrgaoLotacao)
                .HasColumnName("cd_orgao_lotacao")
                .HasComment("Chave primaria autoincremental. Código do registro do órgão de lotação dos usuários");

            entity.Property(e => e.CodOrgao).HasColumnName("cod_orgao");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Indica se o registro foi excluído");

            entity.Property(e => e.NmOrgaoLotacao)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_lotacao")
                .HasComment("Nome do órgão de lotação dos usuários do SICOLA");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbOrgaoLotacao> entity);
    }
}
