// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbPatrimonioFotoConfiguration : IEntityTypeConfiguration<TbPatrimonioFoto>
    {
        public void Configure(EntityTypeBuilder<TbPatrimonioFoto> entity)
        {
            entity.HasKey(e => e.CdPatrimonioFoto);

            entity.ToTable("tb_patrimonio_foto", "dbo");

            entity.HasComment("Fotografias dos bens patrimoniais do IML");

            entity.Property(e => e.CdPatrimonioFoto)
                .HasColumnName("cd_patrimonio_foto")
                .HasComment("Chave primaria autoincremental. Código do registro da fotografia de um bem patrimonial");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu a fotografia do bem patrimonial");

            entity.Property(e => e.CdPatrimonio)
                .HasColumnName("cd_patrimonio")
                .HasComment("Chave estrangeira na tabela tb_patrimonio. Código do patrimônio no cadastro de bens do IML");

            entity.Property(e => e.DtImagem)
                .HasColumnType("datetime")
                .HasColumnName("dt_imagem")
                .HasComment("Data em que a fotografia foi registrada");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão da fotografia do bem");

            entity.Property(e => e.Legenda)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("legenda")
                .HasComment("Descrição da fotografia");

            entity.Property(e => e.NmArquivo)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("nm_arquivo")
                .HasComment("Nome do arquivo JPG gravado na pasta fotopatrimonio");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbPatrimonioFoto> entity);
    }
}
