// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbPalavraConfiguration : IEntityTypeConfiguration<TbPalavra>
    {
        public void Configure(EntityTypeBuilder<TbPalavra> entity)
        {
            entity.HasKey(e => e.CodPalavra);

            entity.ToTable("tb_palavra", "dbo");

            entity.HasComment("Tabela não utilizada no SICOLA. ");

            entity.Property(e => e.CodPalavra)
                .HasColumnName("Cod_Palavra")
                .HasComment("Tabela não utilizada");

            entity.Property(e => e.Conferida)
                .HasMaxLength(1)
                .HasColumnName("conferida")
                .HasComment("Tabela não utilizada");

            entity.Property(e => e.Matricula)
                .HasMaxLength(8)
                .HasColumnName("matricula")
                .HasComment("Tabela não utilizada");

            entity.Property(e => e.Palavra)
                .HasMaxLength(40)
                .HasComment("Tabela não utilizada");

            entity.Property(e => e.Qtde)
                .HasColumnName("qtde")
                .HasComment("Tabela não utilizada");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbPalavra> entity);
    }
}
