// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbPertenceConfiguration : IEntityTypeConfiguration<TbPertence>
    {
        public void Configure(EntityTypeBuilder<TbPertence> entity)
        {
            entity.HasKey(e => e.CdPertence);

            entity.ToTable("tb_pertence", "dbo");

            entity.HasComment("Pertence de cadáver recolhido no IML pelo técnico de necrópsia");

            entity.Property(e => e.CdPertence)
                .HasColumnName("cd_pertence")
                .HasComment("Chave primaria autoincremental. Código do registro do pertence recolhido");

            entity.Property(e => e.CdCadaver)
                .HasColumnName("cd_cadaver")
                .HasComment("Chave estrangeira na tabela tb_cadaver. Código do cadáver dono do pertence");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o pertence do cadáver");

            entity.Property(e => e.DsPertence)
                .HasMaxLength(400)
                .IsUnicode(false)
                .HasColumnName("ds_pertence")
                .HasComment("Descrição do pertence que foi recolhido do cadáver");

            entity.Property(e => e.DtEntrega)
                .HasColumnType("datetime")
                .HasColumnName("dt_entrega")
                .HasComment("Data da entrega do pertence recolhido ao familiar responsável pelo cadáver");

            entity.Property(e => e.DtExclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_exclusao")
                .HasComment("Data da exclusão do registro do pertence recolhido");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do pertence recolhido");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.Excluidor)
                .HasColumnName("excluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o pertence recolhido");

            entity.Property(e => e.HrInclusao)
                .HasColumnType("datetime")
                .HasColumnName("hr_inclusao")
                .HasComment("Hora da inclusão do pertence recolhido. Este campo deixou de ser usado em setembro de 2009.");

            entity.Property(e => e.NmRecebedor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_recebedor")
                .HasComment("Nome do familiar que recebeu o pertence");

            entity.Property(e => e.RgRecebedor)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("rg_recebedor")
                .HasComment("Número do RG do familiar que recebeu o pertence");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbPertence> entity);
    }
}
