// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbProrrogacaoConfiguration : IEntityTypeConfiguration<TbProrrogacao>
    {
        public void Configure(EntityTypeBuilder<TbProrrogacao> entity)
        {
            entity.HasKey(e => e.CdProrrogacao);

            entity.ToTable("tb_prorrogacao", "dbo");

            entity.HasComment("Pedido de prorrogação de prazo para conclusão do laudo. Pedido feito pelo legista. Deixou de ser usado em fevereiro de 2018 a pedido da diretora, Dra Cyntia, e passou a ser feito via ofício.");

            entity.HasIndex(e => e.CdLaudo, "IX_TB_PRORROGACAO_CD_LAUDO")
                .HasFillFactor((byte)85);

            entity.Property(e => e.CdProrrogacao)
                .HasColumnName("cd_prorrogacao")
                .HasComment("Chave primaria autoincremental. Código do registro do pedido de prorrogação de prazo de conclusão de laudo");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo ao qual está solicitando a prorrogação de prazo de conclusão");

            entity.Property(e => e.CdUsuario)
                .HasColumnName("cd_usuario")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que solicitou a prorrogação de prazo");

            entity.Property(e => e.DtPedido)
                .HasColumnType("datetime")
                .HasColumnName("dt_pedido")
                .HasComment("Data da solicitação de prorrogação de prazo");

            entity.Property(e => e.DtTermino)
                .HasColumnType("datetime")
                .HasColumnName("dt_termino")
                .HasComment("Data provável para o término do laudo");

            entity.Property(e => e.Motivo)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("motivo")
                .HasComment("Motivo da solicitação de prorrogação de prazo para conclusão de laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbProrrogacao> entity);
    }
}
