// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbPscPacienteConfiguration : IEntityTypeConfiguration<TbPscPaciente>
    {
        public void Configure(EntityTypeBuilder<TbPscPaciente> entity)
        {
            entity.HasKey(e => e.CdPaciente);

            entity.ToTable("tb_psc_paciente", "dbo");

            entity.HasComment("Pacientes da seção de psicopatologia");

            entity.Property(e => e.CdPaciente)
                .HasColumnName("cd_paciente")
                .HasComment("Chave primaria autoincremental. Código do registro do paciente da psicopatologia");

            entity.Property(e => e.CdExcluidor)
                .HasColumnName("cd_excluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o paciente");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o paciente");

            entity.Property(e => e.DtExclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_exclusao")
                .HasComment("Data da exclusão do registro do paciente");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do registro do paciente");

            entity.Property(e => e.NmMae)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_mae")
                .HasComment("Nome da mãe do paciente da seção de psicopatologia");

            entity.Property(e => e.NmPaciente)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_paciente")
                .HasComment("Nome do paciente da seção de psicopatologia");

            entity.Property(e => e.NmPai)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_pai")
                .HasComment("Nome do pai do paciente da seção de psicopatologia");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbPscPaciente> entity);
    }
}
