// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbRemocaoConfiguration : IEntityTypeConfiguration<TbRemocao>
    {
        public void Configure(EntityTypeBuilder<TbRemocao> entity)
        {
            entity.HasKey(e => e.CdRemocao);

            entity.ToTable("tb_remocao", "dbo");

            entity.HasComment("Servidor da seção de necrópsia que auxiliou na remoção do cadáver");

            entity.Property(e => e.CdRemocao)
                .HasColumnName("cd_remocao")
                .HasComment("Chave primaria autoincremental. Código do registro do servidor que auxiliou na remoção");

            entity.Property(e => e.CdCadaver)
                .HasColumnName("cd_cadaver")
                .HasComment("Chave estrangeira na tabela tb_cadaver. Código cadáver cuja remoção foi auxiliada pelo servidor");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro do auxílio na remoção");

            entity.Property(e => e.CdRemoveu)
                .HasColumnName("cd_removeu")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o registro");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do registro do servidor que auxiliou na remoção do cadáver");

            entity.Property(e => e.HrInclusao)
                .HasColumnType("datetime")
                .HasColumnName("hr_inclusao")
                .HasComment("Hora da inclusão do registro do servidor que auxiliou na remoção do cadáver");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbRemocao> entity);
    }
}
