// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbSapeDespachoConfiguration : IEntityTypeConfiguration<TbSapeDespacho>
    {
        public void Configure(EntityTypeBuilder<TbSapeDespacho> entity)
        {
            entity.HasKey(e => e.CdSapeDespacho);

            entity.ToTable("tb_sape_despacho", "dbo");

            entity.HasComment("Despacho do legista para a seção de protocolo (SAPE)");

            entity.Property(e => e.CdSapeDespacho)
                .HasColumnName("cd_sape_despacho")
                .HasComment("Chave primaria autoincremental. Código do registro do despacho para a SAPE");

            entity.Property(e => e.CdExcluidor)
                .HasColumnName("cd_excluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o despacho");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o despacho");

            entity.Property(e => e.CdRecebedor)
                .HasColumnName("cd_recebedor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que recebeu o despacho na SAPE");

            entity.Property(e => e.Despacho)
                .HasColumnType("text")
                .HasColumnName("despacho")
                .HasComment("Texto do despacho do legista para a SAPE");

            entity.Property(e => e.DtDespacho)
                .HasColumnType("datetime")
                .HasColumnName("dt_despacho")
                .HasComment("Data informada pelo legista para o despacho");

            entity.Property(e => e.DtExclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_exclusao")
                .HasComment("Data da exclusão do despacho");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do despacho");

            entity.Property(e => e.DtRecebido)
                .HasColumnType("datetime")
                .HasColumnName("dt_recebido")
                .HasComment("Data do recebimento do despacho na SAPE");

            entity.Property(e => e.Referencia)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("referencia")
                .HasComment("Número do documento de referência para o despacho");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbSapeDespacho> entity);
    }
}
