// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbSecaoConfiguration : IEntityTypeConfiguration<TbSecao>
    {
        public void Configure(EntityTypeBuilder<TbSecao> entity)
        {
            entity.HasKey(e => e.CdSecao)
                .HasName("PK_tb_secao2");

            entity.ToTable("tb_secao", "dbo");

            entity.HasComment("Texto da seção (parte) do laudo redigido pelo legista");

            entity.Property(e => e.CdSecao)
                .HasColumnName("cd_secao")
                .HasComment("Chave primaria autoincremental. Código do registro do texto da seção do laudo");

            entity.Property(e => e.CdLaudo)
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo ao qual pertence o texto");

            entity.Property(e => e.CdSecaoLaudo)
                .HasColumnName("cd_secao_laudo")
                .HasComment("Chave estrangeira na tabela tb_secao_laudo. Código da seção (parte) do laudo à qual o texto se refere");

            entity.Property(e => e.TextoSecao)
                .IsUnicode(false)
                .HasColumnName("texto_secao")
                .HasComment("Redação do texto feita pelo legista para compor o laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbSecao> entity);
    }
}
