// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbTmbpExternoConfiguration : IEntityTypeConfiguration<TbTmbpExterno>
    {
        public void Configure(EntityTypeBuilder<TbTmbpExterno> entity)
        {
            entity.HasKey(e => e.CdTmbp);

            entity.ToTable("tb_tmbp_externo", "dbo");

            entity.HasComment("Termo de movimentação de bens patrimoniais externo (para fora do IML)");

            entity.Property(e => e.CdTmbp)
                .HasColumnName("cd_tmbp")
                .HasComment("Chave primaria autoincremental. Código do registro do TMBP externo");

            entity.Property(e => e.AnoTmbp)
                .HasColumnName("ano_tmbp")
                .HasComment("Ano do TMBP externo");

            entity.Property(e => e.CdCadastrador)
                .HasColumnName("cd_cadastrador")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o TMBP externo");

            entity.Property(e => e.CdOrgaoDestino)
                .HasColumnName("cd_orgao_destino")
                .HasComment("Chave estrangeira na tabela tb_secao_lotacao. Código do órgão de destino do bem patrimonial");

            entity.Property(e => e.CdOrgaoLotacao)
                .HasColumnName("cd_orgao_lotacao")
                .HasComment("Chave estrangeira na tabela tb_orgao_lotacao. Código do órgão de lotação do usuário que incluiu o TMBP");

            entity.Property(e => e.CdSecaoOrigem)
                .HasColumnName("cd_secao_origem")
                .HasComment("Chave estrangeira na tabela tb_secao_lotacao. Código da seção de origem do bem patrimonial");

            entity.Property(e => e.CdUsuarioOrigem)
                .HasColumnName("cd_usuario_origem")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que assina o TMBP pelo IML");

            entity.Property(e => e.DtMovimento)
                .HasColumnType("datetime")
                .HasColumnName("dt_movimento")
                .HasComment("Data da movimentação do bem patrimonial para fora do IML");

            entity.Property(e => e.ValorTmbp)
                .HasColumnName("valor_tmbp")
                .HasComment("Número único sequencial do TMBP externo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbTmbpExterno> entity);
    }
}
