// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbTpLaudoConfiguration : IEntityTypeConfiguration<TbTpLaudo>
    {
        public void Configure(EntityTypeBuilder<TbTpLaudo> entity)
        {
            entity.HasKey(e => e.CdTpLaudo);

            entity.ToTable("tb_tp_laudo", "dbo");

            entity.HasComment("Tipos de laudos realizados no IML");

            entity.Property(e => e.CdTpLaudo)
                .HasColumnName("cd_tp_laudo")
                .HasComment("Chave primaria autoincremental. Código do registro do tipo de laudo realizado no IML");

            entity.Property(e => e.CorpoDelito)
                .HasColumnName("corpo_delito")
                .HasComment("Informa se o laudo é referente a um exame de corpo de delito ou não");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.NmTpLaudo)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("nm_tp_laudo")
                .HasComment("Nome do tipo de laudo");

            entity.Property(e => e.Prazo)
                .HasColumnName("prazo")
                .HasComment("Tempo em dias para a conclusão do laudo");

            entity.Property(e => e.Preambulo)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("preambulo")
                .HasComment("Texto complementar impresso após o preâmbulo do laudo");

            entity.Property(e => e.TituloTpLaudo)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("titulo_tp_laudo")
                .HasComment("Título colocado acima do tipo do laudo e à esquerda do número do laudo na impressão do laudo");

            entity.Property(e => e.TpExame)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("tp_exame")
                .HasComment("Informa se é um laudo do vivo ( 1 ), do morto ( 2 ) ou ambos ( 3 )");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbTpLaudo> entity);
    }
}
