// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbTpExameLcConfiguration : IEntityTypeConfiguration<TbTpExameLc>
    {
        public void Configure(EntityTypeBuilder<TbTpExameLc> entity)
        {
            entity.HasKey(e => e.CdTpExameLc);

            entity.ToTable("tb_tp_exame_lc", "dbo");

            entity.HasComment("Motivo para realização do exame do laudo de Lesões Corporais");

            entity.Property(e => e.CdTpExameLc)
                .HasColumnName("cd_tp_exame_lc")
                .HasComment("Chave primaria autoincremental. Código do registro do motivo do exame de Lesões Corporais");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.Incluidor)
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro");

            entity.Property(e => e.NmTpExameLc)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("nm_tp_exame_lc")
                .HasComment("Descrição do motivo do exame de Lesões Corporais");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbTpExameLc> entity);
    }
}
