// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbTpExameConfiguration : IEntityTypeConfiguration<TbTpExame>
    {
        public void Configure(EntityTypeBuilder<TbTpExame> entity)
        {
            entity.HasKey(e => e.CdTpExame);

            entity.ToTable("tb_tp_exame", "dbo");

            entity.HasComment("Tipo de exame laboratorial");

            entity.Property(e => e.CdTpExame)
                .HasColumnName("cd_tp_exame")
                .HasComment("Chave primaria autoincremental. Código do registro do tipo de exame laboratorial");

            entity.Property(e => e.Codificacao)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("codificacao")
                .HasComment("Código único que identifica o tipo de exame laboratorial");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.NmTpExame)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_tp_exame")
                .HasComment("Descrição do tipo de exame laboratorial");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbTpExame> entity);
    }
}
