// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbVeiculoFunerariaConfiguration : IEntityTypeConfiguration<TbVeiculoFuneraria>
    {
        public void Configure(EntityTypeBuilder<TbVeiculoFuneraria> entity)
        {
            entity.HasKey(e => e.CdVeiculo);

            entity.ToTable("tb_veiculo_funeraria", "dbo");

            entity.HasComment("Veículo utilizado pela funerária");

            entity.Property(e => e.CdVeiculo)
                .HasColumnName("cd_veiculo")
                .HasComment("Chave primaria autoincremental. Código do registro do veículo utilizado pela funerária");

            entity.Property(e => e.Caracterizado)
                .HasColumnName("caracterizado")
                .HasComment("Informa se o veículo é caracterizado");

            entity.Property(e => e.CdFuneraria)
                .HasColumnName("cd_funeraria")
                .HasComment("Chave estrangeira na tabela tb_funeraria. Código da funerária proprietária do veículo");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o veículo");

            entity.Property(e => e.Credencial)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("credencial")
                .HasComment("Número da credencial do veículo");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do veículo no cadastro do IML");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.MarcaModelo)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("marca_modelo")
                .HasComment("Marca/modelo do veículo da funerária");

            entity.Property(e => e.Placa)
                .HasMaxLength(7)
                .IsUnicode(false)
                .HasColumnName("placa")
                .HasComment("Placa do veículo da funerária");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbVeiculoFuneraria> entity);
    }
}
