// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbVesteConfiguration : IEntityTypeConfiguration<TbVeste>
    {
        public void Configure(EntityTypeBuilder<TbVeste> entity)
        {
            entity.HasKey(e => e.CdVeste);

            entity.ToTable("tb_veste", "dbo");

            entity.HasComment("Usuário que auxiliou na veste do cadáver");

            entity.Property(e => e.CdVeste)
                .HasColumnName("cd_veste")
                .HasComment("Chave primaria autoincremental. Código do registro do usuário auxiliar da veste");

            entity.Property(e => e.CdCadaver)
                .HasColumnName("cd_cadaver")
                .HasComment("Chave estrangeira na tabela tb_cadaver. Código do cadáver que foi vestido pelo usuário");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro do auxílio na veste");

            entity.Property(e => e.CdVestiu)
                .HasColumnName("cd_vestiu")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que auxiliou na veste do cadáver");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do registro de auxílio na veste do cadáver");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbVeste> entity);
    }
}
