// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbViaturaConfiguration : IEntityTypeConfiguration<TbViatura>
    {
        public void Configure(EntityTypeBuilder<TbViatura> entity)
        {
            entity.HasKey(e => e.CdViatura);

            entity.ToTable("tb_viatura", "dbo");

            entity.HasComment("Viatura do IML");

            entity.Property(e => e.CdViatura)
                .HasColumnName("cd_viatura")
                .HasComment("Chave primaria autoincremental. Código do registro da viatura do IML");

            entity.Property(e => e.CdIncluidor)
                .HasColumnName("cd_incluidor")
                .HasComment("Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu a viatura");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do cadastro da viatura");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.Marca)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("marca")
                .HasComment("Marca/modelo da viatura");

            entity.Property(e => e.Placa)
                .HasMaxLength(8)
                .IsUnicode(false)
                .HasColumnName("placa")
                .HasComment("Placa ostentada pela viatura");

            entity.Property(e => e.Prefixo)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("prefixo")
                .HasComment("Prefixo do rádio da viatura");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbViatura> entity);
    }
}
