// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TbViolenciaDomesticaConfiguration : IEntityTypeConfiguration<TbViolenciaDomestica>
    {
        public void Configure(EntityTypeBuilder<TbViolenciaDomestica> entity)
        {
            entity.HasKey(e => e.CdLaudo);

            entity.ToTable("tb_violencia_domestica", "dbo");

            entity.HasComment("Relação de laudos de lesão corporal de mulheres vítimas de violência doméstica (para estatística)");

            entity.Property(e => e.CdLaudo)
                .ValueGeneratedNever()
                .HasColumnName("cd_laudo")
                .HasComment("Chave estrangeira na tabela tb_laudo. Código do laudo da vítima de violência doméstica");

            entity.Property(e => e.Abortou)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("abortou")
                .HasComment("");

            entity.Property(e => e.Autor)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("autor")
                .HasComment("");

            entity.Property(e => e.AutorReside)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("autor_reside")
                .HasComment("");

            entity.Property(e => e.Deficiente)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("deficiente")
                .HasComment("");

            entity.Property(e => e.DtFato)
                .HasColumnType("datetime")
                .HasColumnName("dt_fato")
                .HasComment("Data do acontecimento da violência doméstica");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao")
                .HasComment("Data da inclusão do registro de violência doméstica");

            entity.Property(e => e.Escolaridade)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("escolaridade")
                .HasComment("Escolaridade da mulher vítima da violência doméstica");

            entity.Property(e => e.Excluido)
                .HasColumnName("excluido")
                .HasComment("Informa se o registro foi excluído");

            entity.Property(e => e.FilhoReside)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("filho_reside")
                .HasComment("Informa se algum dos filhos reside com a vítima");

            entity.Property(e => e.Filhos)
                .HasColumnName("filhos")
                .HasComment("Quantidade de filhos da vítima");

            entity.Property(e => e.Gestante)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("gestante")
                .HasComment("Informa se a mulher está gestante");

            entity.Property(e => e.NrEpisodio)
                .HasColumnName("nr_episodio")
                .HasComment("Quantidade de vezes que o episódio se repetiu");

            entity.Property(e => e.TpViolencia)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("tp_violencia")
                .HasComment("");

            entity.Property(e => e.VioDom)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("vio_dom")
                .HasComment("");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TbViolenciaDomestica> entity);
    }
}
