// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TdSolicitacaoImlConfiguration : IEntityTypeConfiguration<TdSolicitacaoIml>
    {
        public void Configure(EntityTypeBuilder<TdSolicitacaoIml> entity)
        {
            entity.HasKey(e => e.CodSolicitacao);

            entity.ToTable("TD_SOLICITACAO_IML", "dbo");

            entity.HasComment("Esta tabela não foi criada no IML, não sei qual a sua utilização.");

            entity.Property(e => e.CodSolicitacao)
                .ValueGeneratedNever()
                .HasColumnName("COD_SOLICITACAO")
                .HasComment("Chave primaria");

            entity.Property(e => e.AditamentoOcorrencia)
                .HasColumnName("ADITAMENTO_OCORRENCIA")
                .HasComment("");

            entity.Property(e => e.AnoOcorrencia)
                .HasColumnName("ANO_OCORRENCIA")
                .HasComment("");

            entity.Property(e => e.CodMatriculaSolicitante)
                .IsRequired()
                .HasMaxLength(7)
                .IsUnicode(false)
                .HasColumnName("COD_MATRICULA_SOLICITANTE")
                .HasComment("")
                .UseCollation("SQL_Latin1_General_CP1_CI_AI");

            entity.Property(e => e.CodPessoaOcorrencia)
                .HasColumnName("COD_PESSOA_OCORRENCIA")
                .HasComment("");

            entity.Property(e => e.CodSeqDocumentosDiversos)
                .HasColumnName("COD_SEQ_DOCUMENTOS_DIVERSOS")
                .HasComment("");

            entity.Property(e => e.CodTipoDocumentoSolicitante)
                .HasColumnName("COD_TIPO_DOCUMENTO_SOLICITANTE")
                .HasComment("");

            entity.Property(e => e.CodUnidadePolicialOcorrencia)
                .HasColumnName("COD_UNIDADE_POLICIAL_OCORRENCIA")
                .HasComment("");

            entity.Property(e => e.CodUnidadePolicialSolicitante)
                .HasColumnName("COD_UNIDADE_POLICIAL_SOLICITANTE")
                .HasComment("");

            entity.Property(e => e.DataHoraDeslocamento)
                .HasColumnType("datetime")
                .HasColumnName("DATA_HORA_DESLOCAMENTO")
                .HasComment("");

            entity.Property(e => e.DataHoraSolicitacao)
                .HasColumnType("datetime")
                .HasColumnName("DATA_HORA_SOLICITACAO")
                .HasComment("");

            entity.Property(e => e.DataNascPessoaOcorrencia)
                .HasColumnType("datetime")
                .HasColumnName("DATA_NASC_PESSOA_OCORRENCIA")
                .HasComment("");

            entity.Property(e => e.NomeMaePessoaOcorrencia)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("NOME_MAE_PESSOA_OCORRENCIA")
                .HasComment("")
                .UseCollation("SQL_Latin1_General_CP1_CI_AI");

            entity.Property(e => e.NomePessoaOcorrencia)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("NOME_PESSOA_OCORRENCIA")
                .HasComment("")
                .UseCollation("SQL_Latin1_General_CP1_CI_AI");

            entity.Property(e => e.NrDocumentoSolicitante)
                .HasColumnName("NR_DOCUMENTO_SOLICITANTE")
                .HasComment("");

            entity.Property(e => e.NrOcorrencia)
                .HasColumnName("NR_OCORRENCIA")
                .HasComment("");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TdSolicitacaoIml> entity);
    }
}
