// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class TipoAnexoConfiguration : IEntityTypeConfiguration<TipoAnexo>
    {
        public void Configure(EntityTypeBuilder<TipoAnexo> entity)
        {
            entity.ToTable("TIPO_ANEXO", "dbo");

            entity.Property(e => e.Descricao).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoAnexo> entity);
    }
}
