// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwAditamentoPeritoIntervaloTempoConfiguration : IEntityTypeConfiguration<VwAditamentoPeritoIntervaloTempo>
    {
        public void Configure(EntityTypeBuilder<VwAditamentoPeritoIntervaloTempo> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_aditamento_perito_intervalo_tempo", "dbo");

            entity.HasComment("Esta consulta não é utilizada no SICOLA");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.Incluidor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("INCLUIDOR");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwAditamentoPeritoIntervaloTempo> entity);
    }
}
