// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwBuscaLaudoPorPalavraNasSecoesConfiguration : IEntityTypeConfiguration<VwBuscaLaudoPorPalavraNasSecoes>
    {
        public void Configure(EntityTypeBuilder<VwBuscaLaudoPorPalavraNasSecoes> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_busca_laudo_por_palavra_nas_secoes", "dbo");

            entity.HasComment("Esta consulta não é utilizada no SICOLA");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.NmTpLaudo)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_tp_laudo");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.TextoSecao)
                .HasColumnType("text")
                .HasColumnName("texto_secao");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwBuscaLaudoPorPalavraNasSecoes> entity);
    }
}
