// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwCadaverConfiguration : IEntityTypeConfiguration<VwCadaver>
    {
        public void Configure(EntityTypeBuilder<VwCadaver> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_cadaver", "dbo");

            entity.HasComment("Informações sobre o cadáver de um laudo. Esta consulta pega todos os campos expressos em códigos e busca seus respectivos registros nas outras tabelas. Por exemplo, em vez de mostrar o código do usuário, mostra o nome do usuário.");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.AnoOcorrencia).HasColumnName("ano_ocorrencia");

            entity.Property(e => e.Anotacao)
                .HasColumnType("text")
                .HasColumnName("anotacao");

            entity.Property(e => e.Cancelado).HasColumnName("cancelado");

            entity.Property(e => e.CdCadaver).HasColumnName("cd_cadaver");

            entity.Property(e => e.CdCartorio).HasColumnName("cd_cartorio");

            entity.Property(e => e.CdCausaJurDp).HasColumnName("cd_causa_jur_dp");

            entity.Property(e => e.CdCausaJurPerito).HasColumnName("cd_causa_jur_perito");

            entity.Property(e => e.CdCausaMedica).HasColumnName("cd_causa_medica");

            entity.Property(e => e.CdCemiterio).HasColumnName("cd_cemiterio");

            entity.Property(e => e.CdCidade).HasColumnName("cd_cidade");

            entity.Property(e => e.CdClinica).HasColumnName("cd_clinica");

            entity.Property(e => e.CdCriouAuto).HasColumnName("cd_criou_auto");

            entity.Property(e => e.CdCriouEntrada).HasColumnName("cd_criou_entrada");

            entity.Property(e => e.CdEstadoCivil).HasColumnName("cd_estado_civil");

            entity.Property(e => e.CdFuneraria).HasColumnName("cd_funeraria");

            entity.Property(e => e.CdHospital).HasColumnName("cd_hospital");

            entity.Property(e => e.CdIncluiuPlantao).HasColumnName("cd_incluiu_plantao");

            entity.Property(e => e.CdInstrumento).HasColumnName("cd_instrumento");

            entity.Property(e => e.CdLaudo).HasColumnName("cd_laudo");

            entity.Property(e => e.CdMotorista).HasColumnName("cd_motorista");

            entity.Property(e => e.CdNacReconhecedor)
                .HasColumnName("cd_nac_reconhecedor")
                .HasComment("Nacionalidade do reconhecedor");

            entity.Property(e => e.CdNatReconhecedor)
                .HasColumnName("cd_nat_reconhecedor")
                .HasComment("Naturalidade do reconhecedor");

            entity.Property(e => e.CdNecropsia)
                .HasColumnName("cd_necropsia")
                .HasComment("auxiliar que fez necropsia");

            entity.Property(e => e.CdPerito).HasColumnName("cd_perito");

            entity.Property(e => e.CdRaioX).HasColumnName("cd_raio_x");

            entity.Property(e => e.CdUf).HasColumnName("cd_uf");

            entity.Property(e => e.CdVeiculo).HasColumnName("cd_veiculo");

            entity.Property(e => e.Cnpj)
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("cnpj");

            entity.Property(e => e.CodLaudo)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("COD_LAUDO");

            entity.Property(e => e.CodOcorrenciaIml)
                .HasMaxLength(18)
                .IsUnicode(false)
                .HasColumnName("COD_OCORRENCIA_IML");

            entity.Property(e => e.CodOrgaoOcorrencia).HasColumnName("cod_orgao_ocorrencia");

            entity.Property(e => e.CpfReconhecedor)
                .HasMaxLength(14)
                .IsUnicode(false)
                .HasColumnName("cpf_reconhecedor");

            entity.Property(e => e.Delegado)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("delegado");

            entity.Property(e => e.DtEntradaIml)
                .HasColumnType("datetime")
                .HasColumnName("dt_entrada_iml");

            entity.Property(e => e.DtFimNecropsia)
                .HasColumnType("datetime")
                .HasColumnName("dt_fim_necropsia");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.DtInicioNecropsia)
                .HasColumnType("datetime")
                .HasColumnName("dt_inicio_necropsia");

            entity.Property(e => e.DtLaudo)
                .HasColumnType("datetime")
                .HasColumnName("dt_laudo");

            entity.Property(e => e.DtNascimento)
                .HasColumnType("datetime")
                .HasColumnName("dt_nascimento");

            entity.Property(e => e.DtPedidoRemocao)
                .HasColumnType("datetime")
                .HasColumnName("dt_pedido_remocao");

            entity.Property(e => e.DtReconhecido)
                .HasColumnType("datetime")
                .HasColumnName("dt_reconhecido");

            entity.Property(e => e.DtSaida)
                .HasColumnType("datetime")
                .HasColumnName("dt_saida");

            entity.Property(e => e.Embalsamamento).HasColumnName("embalsamamento");

            entity.Property(e => e.EndFuneraria)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("end_funeraria");

            entity.Property(e => e.EndReconhecedor)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("end_reconhecedor");

            entity.Property(e => e.Formolizacao).HasColumnName("formolizacao");

            entity.Property(e => e.HrInclusao)
                .HasColumnType("datetime")
                .HasColumnName("hr_inclusao");

            entity.Property(e => e.HrReconhecido)
                .HasColumnType("datetime")
                .HasColumnName("hr_reconhecido");

            entity.Property(e => e.Local)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("local");

            entity.Property(e => e.LocalRemocao)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("local_remocao");

            entity.Property(e => e.MaeReconhecedor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("mae_reconhecedor");

            entity.Property(e => e.MarcaModelo)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("marca_modelo");

            entity.Property(e => e.Nascimento)
                .HasColumnType("datetime")
                .HasColumnName("nascimento");

            entity.Property(e => e.NmCartorio)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_cartorio");

            entity.Property(e => e.NmCausaJurDp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_causa_jur_dp");

            entity.Property(e => e.NmCausaJurPerito)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_causa_jur_perito");

            entity.Property(e => e.NmCausaMedica)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_causa_medica");

            entity.Property(e => e.NmCemiterio)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_cemiterio");

            entity.Property(e => e.NmCidade)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_cidade");

            entity.Property(e => e.NmCriouEntrada)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_criou_entrada");

            entity.Property(e => e.NmDocumento)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_documento");

            entity.Property(e => e.NmEstado)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_estado");

            entity.Property(e => e.NmFuneraria)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_funeraria");

            entity.Property(e => e.NmHospital)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nm_hospital");

            entity.Property(e => e.NmIncluiuPlantao)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_incluiu_plantao");

            entity.Property(e => e.NmInstrumento)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("nm_instrumento");

            entity.Property(e => e.NmMae)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_mae");

            entity.Property(e => e.NmMotorista)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_motorista");

            entity.Property(e => e.NmNecropsia)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_necropsia");

            entity.Property(e => e.NmOrgaoExpedidor)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_expedidor");

            entity.Property(e => e.NmOrgaoOcorrencia)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_ocorrencia");

            entity.Property(e => e.NmPai)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_pai");

            entity.Property(e => e.NmPericiando)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_periciando");

            entity.Property(e => e.NmPerito1)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_perito1");

            entity.Property(e => e.NmPeritoCadaver)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_perito_cadaver");

            entity.Property(e => e.NmReconhecedor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_reconhecedor");

            entity.Property(e => e.NmSexo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_sexo");

            entity.Property(e => e.NmTpLaudo)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("nm_tp_laudo");

            entity.Property(e => e.NrDeclaracao).HasColumnName("nr_declaracao");

            entity.Property(e => e.NrDocumento)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nr_documento");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.NrOcorrencia).HasColumnName("nr_ocorrencia");

            entity.Property(e => e.Ornamentacao).HasColumnName("ornamentacao");

            entity.Property(e => e.PaiReconhecedor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("pai_reconhecedor");

            entity.Property(e => e.Parentesco)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("parentesco");

            entity.Property(e => e.Placa)
                .HasMaxLength(7)
                .IsUnicode(false)
                .HasColumnName("placa");

            entity.Property(e => e.QtProjetis).HasColumnName("qt_projetis");

            entity.Property(e => e.RgReconhecedor)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("rg_reconhecedor");

            entity.Property(e => e.Telefone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("telefone");

            entity.Property(e => e.TelefoneFuneraria)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("telefone_funeraria");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwCadaver> entity);
    }
}
