// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwEstatErroConfiguration : IEntityTypeConfiguration<VwEstatErro>
    {
        public void Configure(EntityTypeBuilder<VwEstatErro> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_estat_erro", "dbo");

            entity.HasComment("Estatística de erros em laudos pelos servidores da recepção do IML");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.CdEstatErro).HasColumnName("cd_estat_erro");

            entity.Property(e => e.CdHomologou).HasColumnName("cd_homologou");

            entity.Property(e => e.CdIncluidor).HasColumnName("cd_incluidor");

            entity.Property(e => e.CdLaudo).HasColumnName("cd_laudo");

            entity.Property(e => e.DtIncluiu)
                .HasColumnType("datetime")
                .HasColumnName("dt_incluiu");

            entity.Property(e => e.DtLaudo)
                .HasColumnType("datetime")
                .HasColumnName("dt_laudo");

            entity.Property(e => e.NmHomologou)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_homologou");

            entity.Property(e => e.NmIncluidor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_incluidor");

            entity.Property(e => e.NmTpLaudo)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("nm_tp_laudo");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwEstatErro> entity);
    }
}
