// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwHomonimoConfiguration : IEntityTypeConfiguration<VwHomonimo>
    {
        public void Configure(EntityTypeBuilder<VwHomonimo> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_homonimo", "dbo");

            entity.HasComment("Laudos dos últimos 30 dias. Essa listagem é utilizada no sicola para procurar outros laudos de um mesmo periciando no período de 30 dias.");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.CdLaudo)
                .ValueGeneratedOnAdd()
                .HasColumnName("cd_laudo");

            entity.Property(e => e.DtLaudo)
                .HasColumnType("datetime")
                .HasColumnName("dt_laudo");

            entity.Property(e => e.NmMae)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_mae");

            entity.Property(e => e.NmPericiando)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_periciando");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwHomonimo> entity);
    }
}
