// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwIgnoradoFichaConfiguration : IEntityTypeConfiguration<VwIgnoradoFicha>
    {
        public void Configure(EntityTypeBuilder<VwIgnoradoFicha> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_ignorado_ficha", "dbo");

            entity.HasComment("Ficha com características do cadáver classificado como ignorado (sem identificação) pela seção de necrópsia");

            entity.Property(e => e.Adereco)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("adereco");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.Assimetria)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("assimetria");

            entity.Property(e => e.CdCorCabelo).HasColumnName("cd_cor_cabelo");

            entity.Property(e => e.CdCorPele).HasColumnName("cd_cor_pele");

            entity.Property(e => e.CdIgnoradoFicha).HasColumnName("cd_ignorado_ficha");

            entity.Property(e => e.CdIncluidor).HasColumnName("cd_incluidor");

            entity.Property(e => e.CdLaudo).HasColumnName("cd_laudo");

            entity.Property(e => e.CdSexo).HasColumnName("cd_sexo");

            entity.Property(e => e.CdTpCabelo).HasColumnName("cd_tp_cabelo");

            entity.Property(e => e.Cicatriz)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("cicatriz");

            entity.Property(e => e.Cirurgia)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("cirurgia");

            entity.Property(e => e.Dente)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("dente");

            entity.Property(e => e.DtIncluiu)
                .HasColumnType("datetime")
                .HasColumnName("dt_incluiu");

            entity.Property(e => e.DtLocalizado)
                .HasColumnType("datetime")
                .HasColumnName("dt_localizado");

            entity.Property(e => e.DtMorte)
                .HasColumnType("datetime")
                .HasColumnName("dt_morte");

            entity.Property(e => e.Esmalte)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("esmalte");

            entity.Property(e => e.Estatura).HasColumnName("estatura");

            entity.Property(e => e.Excluido).HasColumnName("excluido");

            entity.Property(e => e.Fratura)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("fratura");

            entity.Property(e => e.Idade).HasColumnName("idade");

            entity.Property(e => e.Identificado).HasColumnName("identificado");

            entity.Property(e => e.Local)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("local");

            entity.Property(e => e.NmCorCabelo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_cor_cabelo");

            entity.Property(e => e.NmCorPele)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_cor_pele");

            entity.Property(e => e.NmIncluidor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_incluidor");

            entity.Property(e => e.NmPericiando)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_periciando");

            entity.Property(e => e.NmSexo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_sexo");

            entity.Property(e => e.NmTpCabelo)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("nm_tp_cabelo");

            entity.Property(e => e.NrCalcado).HasColumnName("nr_calcado");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.Obs)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("obs");

            entity.Property(e => e.Peso).HasColumnName("peso");

            entity.Property(e => e.Protese)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("protese");

            entity.Property(e => e.Sinal)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("sinal");

            entity.Property(e => e.Tatuagem)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("tatuagem");

            entity.Property(e => e.Veste)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("veste");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwIgnoradoFicha> entity);
    }
}
