// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwLaudosPorPlantonistaConfiguration : IEntityTypeConfiguration<VwLaudosPorPlantonista>
    {
        public void Configure(EntityTypeBuilder<VwLaudosPorPlantonista> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_laudos_por_plantonista", "dbo");

            entity.HasComment("Esta consulta não é utilizada no SICOLA");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.Usuario)
                .HasMaxLength(111)
                .IsUnicode(false)
                .HasColumnName("usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwLaudosPorPlantonista> entity);
    }
}
