// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwLaudoIiConfiguration : IEntityTypeConfiguration<VwLaudoIi>
    {
        public void Configure(EntityTypeBuilder<VwLaudoIi> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_laudo_ii", "dbo");

            entity.HasComment("Pedidos de identificação de cadáver feito ao papiloscopista do ii");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.AnoLaudoIi).HasColumnName("ano_laudo_ii");

            entity.Property(e => e.CadaverLiberado).HasColumnName("cadaver_liberado");

            entity.Property(e => e.Cancelado).HasColumnName("cancelado");

            entity.Property(e => e.CdIncluidor).HasColumnName("cd_incluidor");

            entity.Property(e => e.CdLaudo).HasColumnName("cd_laudo");

            entity.Property(e => e.CdLaudoIi).HasColumnName("cd_laudo_ii");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.Liberador).HasColumnName("liberador");

            entity.Property(e => e.NmLiberador)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_liberador");

            entity.Property(e => e.NmPericiando)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_periciando");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.NrLaudoIi).HasColumnName("nr_laudo_ii");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwLaudoIi> entity);
    }
}
