// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwLaudoIiPeritoConfiguration : IEntityTypeConfiguration<VwLaudoIiPerito>
    {
        public void Configure(EntityTypeBuilder<VwLaudoIiPerito> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_laudo_ii_perito", "dbo");

            entity.HasComment("Papiloscopistas que confirmaram a identificação do cadáver");

            entity.Property(e => e.CdLaudoIi).HasColumnName("cd_laudo_ii");

            entity.Property(e => e.CdPeritoIi).HasColumnName("cd_perito_ii");

            entity.Property(e => e.Matricula)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("matricula");

            entity.Property(e => e.NmPerito)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_perito");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwLaudoIiPerito> entity);
    }
}
