// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwLaudoMesAtualConfiguration : IEntityTypeConfiguration<VwLaudoMesAtual>
    {
        public void Configure(EntityTypeBuilder<VwLaudoMesAtual> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_laudo_mes_atual", "dbo");

            entity.HasComment("Total de laudos feitos no mês atual");

            entity.Property(e => e.CdIncluidor).HasColumnName("cd_incluidor");

            entity.Property(e => e.DtLaudo)
                .HasColumnType("datetime")
                .HasColumnName("dt_laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwLaudoMesAtual> entity);
    }
}
