// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwLogPesquisaLaudoConfiguration : IEntityTypeConfiguration<VwLogPesquisaLaudo>
    {
        public void Configure(EntityTypeBuilder<VwLogPesquisaLaudo> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_log_pesquisa_laudo", "dbo");

            entity.HasComment("Registro de critérios de pesquisa de laudos realizados no SICOLA");

            entity.Property(e => e.CdLog).HasColumnName("cd_log");

            entity.Property(e => e.CdUsuario).HasColumnName("cd_usuario");

            entity.Property(e => e.Criterio)
                .HasMaxLength(1000)
                .IsUnicode(false)
                .HasColumnName("criterio");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.Ip)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("ip");

            entity.Property(e => e.NmOrgaoLotacao)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_lotacao");

            entity.Property(e => e.NmUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_usuario");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwLogPesquisaLaudo> entity);
    }
}
