// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwLogVisualizaJustificaConfiguration : IEntityTypeConfiguration<VwLogVisualizaJustifica>
    {
        public void Configure(EntityTypeBuilder<VwLogVisualizaJustifica> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_log_visualiza_justifica", "dbo");

            entity.HasComment("Justificativa de usuários externos para visualizar laudos. Deixou de ser usado em 21/09/2009");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.CdLaudo).HasColumnName("cd_laudo");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.Justificativa)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("justificativa");

            entity.Property(e => e.Matricula)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("matricula");

            entity.Property(e => e.NmUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_usuario");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwLogVisualizaJustifica> entity);
    }
}
