// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwPeFilaConfiguration : IEntityTypeConfiguration<VwPeFila>
    {
        public void Configure(EntityTypeBuilder<VwPeFila> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_pe_fila", "dbo");

            entity.HasComment("Fila de legistas para deslocamento emergencial fora do IML. Ordenada pela quantidade de deslocamentos já realizados e pela matrícula");

            entity.Property(e => e.CdUsuario).HasColumnName("cd_usuario");

            entity.Property(e => e.DtLaudo)
                .HasColumnType("datetime")
                .HasColumnName("dt_laudo");

            entity.Property(e => e.Guerra)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("guerra");

            entity.Property(e => e.Matricula)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("matricula");

            entity.Property(e => e.NmUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_usuario");

            entity.Property(e => e.Pontuacao).HasColumnName("pontuacao");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwPeFila> entity);
    }
}
