// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwPedidoMaterialSecaoConfiguration : IEntityTypeConfiguration<VwPedidoMaterialSecao>
    {
        public void Configure(EntityTypeBuilder<VwPedidoMaterialSecao> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_pedido_material_secao", "dbo");

            entity.HasComment("Esta consulta não é utilizada pelo SICOLA");

            entity.Property(e => e.CodMaterial).HasColumnName("Cod_Material");

            entity.Property(e => e.CodPedido).HasColumnName("Cod_Pedido");

            entity.Property(e => e.CodSecao).HasColumnName("Cod_Secao");

            entity.Property(e => e.DataPedido)
                .HasColumnType("datetime")
                .HasColumnName("Data_Pedido");

            entity.Property(e => e.DescMaterial)
                .HasMaxLength(250)
                .HasColumnName("Desc_Material");

            entity.Property(e => e.QuantidadeAtendida).HasColumnName("Quantidade_Atendida");

            entity.Property(e => e.QuantidadePedida).HasColumnName("Quantidade_Pedida");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwPedidoMaterialSecao> entity);
    }
}
