// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwPertenceConfiguration : IEntityTypeConfiguration<VwPertence>
    {
        public void Configure(EntityTypeBuilder<VwPertence> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_pertence", "dbo");

            entity.HasComment("Pertence de cadáver recolhido no IML pelo técnico de necrópsia");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.CdCadaver).HasColumnName("cd_cadaver");

            entity.Property(e => e.CdIncluidor).HasColumnName("cd_incluidor");

            entity.Property(e => e.CdPertence).HasColumnName("cd_pertence");

            entity.Property(e => e.DsPertence)
                .HasMaxLength(400)
                .IsUnicode(false)
                .HasColumnName("ds_pertence");

            entity.Property(e => e.DtEntrega)
                .HasColumnType("datetime")
                .HasColumnName("dt_entrega");

            entity.Property(e => e.DtExclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_exclusao");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.Excluido).HasColumnName("excluido");

            entity.Property(e => e.Excluidor).HasColumnName("excluidor");

            entity.Property(e => e.HrInclusao)
                .HasColumnType("datetime")
                .HasColumnName("hr_inclusao");

            entity.Property(e => e.NmDestinatario)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_destinatario");

            entity.Property(e => e.NmDocumento)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_documento");

            entity.Property(e => e.NmOrgaoExpedidor)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_expedidor");

            entity.Property(e => e.NmPericiando)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_periciando");

            entity.Property(e => e.NmRecebedor)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_recebedor");

            entity.Property(e => e.NrDocumento)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nr_documento");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.RgRecebedor)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("rg_recebedor");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwPertence> entity);
    }
}
