// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwRadiologicoConfiguration : IEntityTypeConfiguration<VwRadiologico>
    {
        public void Configure(EntityTypeBuilder<VwRadiologico> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_radiologico", "dbo");

            entity.HasComment("Pedidos de exame radiológico. Este recurso não é utilizado desde 2009.");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.AnoOcorrencia).HasColumnName("ano_ocorrencia");

            entity.Property(e => e.Cancelado).HasColumnName("cancelado");

            entity.Property(e => e.CdLaudo).HasColumnName("cd_laudo");

            entity.Property(e => e.CdPeritoRadio).HasColumnName("cd_perito_radio");

            entity.Property(e => e.CdRadiologico).HasColumnName("cd_radiologico");

            entity.Property(e => e.CdSolicitante).HasColumnName("cd_solicitante");

            entity.Property(e => e.DtArquivado)
                .HasColumnType("datetime")
                .HasColumnName("dt_arquivado");

            entity.Property(e => e.DtHomologacao)
                .HasColumnType("datetime")
                .HasColumnName("dt_homologacao");

            entity.Property(e => e.DtInicio)
                .HasColumnType("datetime")
                .HasColumnName("dt_inicio");

            entity.Property(e => e.DtNascimento)
                .HasColumnType("datetime")
                .HasColumnName("dt_nascimento");

            entity.Property(e => e.DtSolicitacao)
                .HasColumnType("datetime")
                .HasColumnName("dt_solicitacao");

            entity.Property(e => e.DtTermino)
                .HasColumnType("datetime")
                .HasColumnName("dt_termino");

            entity.Property(e => e.MtSolicitante)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mt_solicitante");

            entity.Property(e => e.NmDestinatario)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_destinatario");

            entity.Property(e => e.NmOrgaoExpedidor)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_expedidor");

            entity.Property(e => e.NmOrgaoOcorrencia)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_ocorrencia");

            entity.Property(e => e.NmPericiando)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_periciando");

            entity.Property(e => e.NmPeritoRadio)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_perito_radio");

            entity.Property(e => e.NmProfissao)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_profissao");

            entity.Property(e => e.NmSexo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_sexo");

            entity.Property(e => e.NmSolicitante)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_solicitante");

            entity.Property(e => e.NmTpDocumento)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_tp_documento");

            entity.Property(e => e.NrDocumento)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nr_documento");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.NrOcorrencia).HasColumnName("nr_ocorrencia");

            entity.Property(e => e.Pedido)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("pedido");

            entity.Property(e => e.Resposta)
                .HasMaxLength(2000)
                .IsUnicode(false)
                .HasColumnName("resposta");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwRadiologico> entity);
    }
}
