// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwRespostaSubstanciaConfiguration : IEntityTypeConfiguration<VwRespostaSubstancia>
    {
        public void Configure(EntityTypeBuilder<VwRespostaSubstancia> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_resposta_substancia", "dbo");

            entity.HasComment("Resposta padronizada para exame laboratorial de uma substância");

            entity.Property(e => e.CdRespostaSubstancia).HasColumnName("cd_resposta_substancia");

            entity.Property(e => e.CdSubstancia).HasColumnName("cd_substancia");

            entity.Property(e => e.Excluido).HasColumnName("excluido");

            entity.Property(e => e.NmResposta)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_resposta");

            entity.Property(e => e.NmSubstancia)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_substancia");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwRespostaSubstancia> entity);
    }
}
