// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwRxConfiguration : IEntityTypeConfiguration<VwRx>
    {
        public void Configure(EntityTypeBuilder<VwRx> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_rx", "dbo");

            entity.HasComment("Registro de raio X realizado em um cadáver");

            entity.Property(e => e.CdCadaver).HasColumnName("cd_cadaver");

            entity.Property(e => e.CdFezRx).HasColumnName("cd_fez_rx");

            entity.Property(e => e.CdIncluidor).HasColumnName("cd_incluidor");

            entity.Property(e => e.CdRx).HasColumnName("cd_rx");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.NmFezRx)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_fez_rx");

            entity.Property(e => e.QtdeFilmes).HasColumnName("qtde_filmes");

            entity.Property(e => e.QtdeProjetis).HasColumnName("qtde_projetis");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwRx> entity);
    }
}
