// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwSecaoOrgaoConfiguration : IEntityTypeConfiguration<VwSecaoOrgao>
    {
        public void Configure(EntityTypeBuilder<VwSecaoOrgao> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_secao_orgao", "dbo");

            entity.HasComment("Relacionamento entre a tabela de órgãos (tb_orgao_lotacao) e a tabela de seções (tb_secao_lotacao), para indicar ao SICOLA a qual órgão pertencem as seções.");

            entity.Property(e => e.CdOrgaoLotacao).HasColumnName("cd_orgao_lotacao");

            entity.Property(e => e.CdSecaoLotacao).HasColumnName("cd_secao_lotacao");

            entity.Property(e => e.NmOrgaoLotacao)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_lotacao");

            entity.Property(e => e.NmSecaoLotacao)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nm_secao_lotacao");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwSecaoOrgao> entity);
    }
}
