// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwTempPudorBConfiguration : IEntityTypeConfiguration<VwTempPudorB>
    {
        public void Configure(EntityTypeBuilder<VwTempPudorB> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_temp_pudor_b", "dbo");

            entity.HasComment("Esta consulta não é utilizada no SICOLA");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.NmQuesito)
                .HasMaxLength(400)
                .IsUnicode(false)
                .HasColumnName("nm_quesito");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            entity.Property(e => e.Resposta)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("resposta");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwTempPudorB> entity);
    }
}
