// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwTempCyntiaMortesELaboratConfiguration : IEntityTypeConfiguration<VwTempCyntiaMortesELaborat>
    {
        public void Configure(EntityTypeBuilder<VwTempCyntiaMortesELaborat> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_temp_cyntia_mortes_e_laborat", "dbo");

            entity.HasComment("Esta consulta não é utilizada no SICOLA");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.CausaJurDp)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Causa Jur DP");

            entity.Property(e => e.CdLaudo).HasColumnName("cd_laudo");

            entity.Property(e => e.CdToxicologico).HasColumnName("cd_toxicologico");

            entity.Property(e => e.DtLaudo)
                .HasColumnType("datetime")
                .HasColumnName("dt_laudo");

            entity.Property(e => e.NmCausaJuridica)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_causa_juridica");

            entity.Property(e => e.NmCausaMedica)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nm_causa_medica");

            entity.Property(e => e.NmResposta)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_resposta");

            entity.Property(e => e.NmSubstancia)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_substancia");

            entity.Property(e => e.NrLaudo).HasColumnName("nr_laudo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwTempCyntiaMortesELaborat> entity);
    }
}
