// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwTempNaoPmlEditouLaudoConfiguration : IEntityTypeConfiguration<VwTempNaoPmlEditouLaudo>
    {
        public void Configure(EntityTypeBuilder<VwTempNaoPmlEditouLaudo> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_temp_nao_pml_editou_laudo", "dbo");

            entity.HasComment("Esta consulta não é utilizada no SICOLA");

            entity.Property(e => e.AnoLaudo).HasColumnName("ano_laudo");

            entity.Property(e => e.DtInclusao)
                .HasColumnType("datetime")
                .HasColumnName("dt_inclusao");

            entity.Property(e => e.Laudo)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasColumnName("laudo");

            entity.Property(e => e.Matricula)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("matricula");

            entity.Property(e => e.NmUsuario)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nm_usuario");

            entity.Property(e => e.TxtAntigo)
                .HasColumnType("text")
                .HasColumnName("txt_antigo");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwTempNaoPmlEditouLaudo> entity);
    }
}
