// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using PCDF.Servico.Sicola.API.Data.Context;
using PCDF.Servico.Sicola.API.Data.Data.Sicola;
using System;

namespace PCDF.Servico.Sicola.API.Data.Context.Configurations
{
    public partial class VwTempAcidenteTransitoConfiguration : IEntityTypeConfiguration<VwTempAcidenteTransito>
    {
        public void Configure(EntityTypeBuilder<VwTempAcidenteTransito> entity)
        {
            entity.HasNoKey();

            entity.ToView("vw_temp_acidente_transito", "dbo");

            entity.HasComment("Esta consulta não é utilizada no SICOLA");

            entity.Property(e => e.DtLaudo)
                .HasColumnType("datetime")
                .HasColumnName("dt_laudo");

            entity.Property(e => e.Laudo)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.NmOrgaoOcorrencia)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("nm_orgao_ocorrencia");

            entity.Property(e => e.NmSexo)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nm_sexo");

            entity.Property(e => e.Ocorrencia)
                .HasMaxLength(15)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VwTempAcidenteTransito> entity);
    }
}
