// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    public partial class IdxDataHora
    {
        public double DataHora { get; set; }
        public int? Data { get; set; }
        public int? Hora { get; set; }
        public string Objetos { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}