// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    public partial class IdxPalavras
    {
        public int IdPalavra { get; set; }
        public int IdDoc { get; set; }
        public int Secao { get; set; }
        public int Deslocamento { get; set; }
        public int? PosicaoInicial { get; set; }
        public int? PosicaoFinal { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}