// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Registrava o recebimento de anexos dos laudos na seção de protocolo, Não é mais utilizada.	
    /// </summary>
    public partial class TbAnexo
    {
        /// <summary>
        /// Chave primaria. Código do anexo que será recebido na seção de protocolo.
        /// </summary>
        public int CdAnexo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do documento (laudo, relatório ou SVO)
        /// </summary>
        public int CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que homologou o anexo.
        /// </summary>
        public int? CdHomologador { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que arquivou o anexo.
        /// </summary>
        public int? CdArquivador { get; set; }
        /// <summary>
        /// Data da homologação do anexo.
        /// </summary>
        public DateTime? DtHomologado { get; set; }
        /// <summary>
        /// Hora da homologação do anexo
        /// </summary>
        public DateTime? HrHomologado { get; set; }
        /// <summary>
        /// Data do arquivamento do anexo
        /// </summary>
        public DateTime? DtArquivado { get; set; }
        /// <summary>
        /// Hora do arquivamento do anexo.
        /// </summary>
        public DateTime? HrArquivado { get; set; }
        /// <summary>
        /// Quantidade de folhas contidas no anexo que será recebido pela seção de protocolo.
        /// </summary>
        public int? NrFolhas { get; set; }
        /// <summary>
        /// Informações adicionais (observações) sobre o anexo.
        /// </summary>
        public string Obs { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}