// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Pedidos de retenção (não liberação) de um cadáver, para evitar a saída do IML por algum motivo.
    /// 
    /// </summary>
    public partial class TbCadaverRetencao
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do pedido de retenção de um cadáver.
        /// </summary>
        public int CdRetencao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo (ou SVO) ao qual se refere o cadáver.
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Data da solicitação de retenção do cadáver.
        /// </summary>
        public DateTime? DtRetencao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que solicitou a retenção do cadáver.
        /// </summary>
        public int? CdReteve { get; set; }
        /// <summary>
        /// Motivo da retenção do cadáver.
        /// </summary>
        public string Motivo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que liberou o cadáver.
        /// </summary>
        public int? CdLiberou { get; set; }
        /// <summary>
        /// Data da liberação da retenção do cadáver.
        /// </summary>
        public DateTime? DtLiberou { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído.
        /// </summary>
        public string Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}