// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Registro de usuários que auxiliaram no descarregamento de um corpo ao chegar o rabecão ao IML
    /// </summary>
    public partial class TbDescarrega
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do usuário que auxiliou no descarregamento do corpo
        /// </summary>
        public int CdDescarrega { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cadaver. Código do cadáver que foi descarregado do rabecão
        /// </summary>
        public int? CdCadaver { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro do auxílio ao descarregamento
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão do registro na tabela
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Hora da inclusao do registro na tabela. A partir de 29/08/2007 a hora passou a ser registrada junto à data no campo acima
        /// </summary>
        public DateTime? HrInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que auxiliou no descarregamento do cadáver
        /// </summary>
        public int? CdDescarregou { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}