// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Tabela não utilizada no SICOLA. Ela seria utilizada para importar dados de um sistema antigo em ACCESS. Nunca foi utilizada.
    /// </summary>
    public partial class TbDocDa
    {
        /// <summary>
        /// Chave primaria
        /// </summary>
        public int CdDocDa { get; set; }
        public int? CdTpDocDa { get; set; }
        public int? Numero { get; set; }
        public int? CdSecaoEmite { get; set; }
        public int? CdIncluiu { get; set; }
        public DateTime? DtIncluiu { get; set; }
        public string Destino { get; set; }
        public string Assunto { get; set; }
        public string Obs { get; set; }
        public string Protocolo { get; set; }
        public bool? Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}