// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Servidores do IML que formam a fila para recebimento de documentos encaminhados pela SAPE, normalmente são os legistas. Aparentemente este recurso do SICOLA nunca foi utilizado.
    /// </summary>
    public partial class TbDocsFila
    {
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que está na fila
        /// </summary>
        public int CdUsuario { get; set; }
        /// <summary>
        /// Número de ordem do usuário na fila de recebimento de documentos. É este número que classifica a lista.
        /// </summary>
        public short? Ordem { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}