// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Escala de deslocamento emergencial dos legistas. Os registros dessa tabela são incluídos e excluídos constantemente, não há opção de alteração de um registro.
    /// </summary>
    public partial class TbEscala
    {
        /// <summary>
        /// Campo autoincremental. Código do registro da escala do legista no deslocamento emergencial
        /// </summary>
        public int CdEscala { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário escalado para deslocamento emergencial.
        /// </summary>
        public int CdUsuario { get; set; }
        /// <summary>
        /// Data/hora da escala do usuário para o deslocamento emergencial
        /// </summary>
        public DateTime DtEscala { get; set; }
        /// <summary>
        /// Tipo de escala, se é para perícia do vivo ou do morto.
        /// </summary>
        public string TpEscala { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}