// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Fotos para ilustrar laudos de cadáveres não identificados.
    /// </summary>
    public partial class TbFotoIgnorado
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da foto de um cadáver não identificado.
        /// </summary>
        public int CdFoto { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo ao qual a fotografia ficará vinculada
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário incluidor da foto do cadáver ignorado
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão da foto do cadáver ignorado
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Nome do arquivo JPG que foi gravado na pasta IGNORADOS
        /// </summary>
        public string NmArquivo { get; set; }
        /// <summary>
        /// Informa se o registro da foto foi excluido
        /// </summary>
        public bool? Excluido { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o registro da foto do cadáver não identificado
        /// </summary>
        public int? CdExcluidor { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}