// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Fotografias destinadas à revelação e impressão no laboratório fotográfico. Deixou de ser utilizado quando as fotos passaram a ser digitais.
    /// </summary>
    public partial class TbFotoImprimir
    {
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo ao qual está vinculada a fotografia a ser impressa
        /// </summary>
        public int CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do legista que solicitou a revelação e impressão da fotografia
        /// </summary>
        public int CdPerito1 { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}