// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Gráfico humanóide para ilustrar os laudos
    /// </summary>
    public partial class TbGrafico
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do gráfico JPG enviado ao servidor
        /// </summary>
        public int CdGrafico { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo ao qual está vinculada a imagem JPG do gráfico
        /// </summary>
        public int CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que enviou (upload) a imagem JPG do gráfico
        /// </summary>
        public int CdIncluidor { get; set; }
        /// <summary>
        /// Data do envio do gráfico para o servidor
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Nome do arquivo JPG enviado por upload para a pasta FOTOS/GRAFICOS
        /// </summary>
        public string NmArquivo { get; set; }
        /// <summary>
        /// Informa se o registro do gráfico foi escluído
        /// </summary>
        public bool? Excluido { get; set; }
        public byte[] Imagem { get; set; }
        public DateTime? DtUpdateFilesystem { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}