// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Tabela básica de hospital de onde o cadáver foi recolhido
    /// </summary>
    public partial class TbHospital
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do hospital
        /// </summary>
        public int CdHospital { get; set; }
        /// <summary>
        /// Nome do hospital de onde o cadáver foi recolhido
        /// </summary>
        public string NmHospital { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}