// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Ficha com características do cadáver classificado como ignorado (sem identificação) pela seção de necrópsia
    /// </summary>
    public partial class TbIgnoradoFicha
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da ficha com dados do cadáver ignorado
        /// </summary>
        public int CdIgnoradoFicha { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo cadavérico ao qual pertence a ficha
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Peso do cadáver em kg
        /// </summary>
        public short? Peso { get; set; }
        /// <summary>
        /// Estatura do cadáver em cm
        /// </summary>
        public short? Estatura { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cor_pele. Código da cor da pele do cadáver
        /// </summary>
        public int? CdCorPele { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cor_cabelo. Código da cor do cabelo do cadáver
        /// </summary>
        public int? CdCorCabelo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cor_cabelo. Código do tipo do cabelo do cadáver
        /// </summary>
        public int? CdTpCabelo { get; set; }
        /// <summary>
        /// Descrição das vestes encontradas com o cadáver
        /// </summary>
        public string Veste { get; set; }
        /// <summary>
        /// Descrição dos adereços encontrados com o cadáver
        /// </summary>
        public string Adereco { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_sexo. Código do sexo do cadáver
        /// </summary>
        public int? CdSexo { get; set; }
        /// <summary>
        /// Idade aproximada do cadáver em anos
        /// </summary>
        public short? Idade { get; set; }
        /// <summary>
        /// Número do calçado utilizado pelo cadáver
        /// </summary>
        public short? NrCalcado { get; set; }
        /// <summary>
        /// Descrição de cicatrizes encontradas no cadáver
        /// </summary>
        public string Cicatriz { get; set; }
        /// <summary>
        /// Descrição de fraturas encontradas no cadáver
        /// </summary>
        public string Fratura { get; set; }
        /// <summary>
        /// Informações sobre a dentição do cadáver
        /// </summary>
        public string Dente { get; set; }
        /// <summary>
        /// Data da localização do cadáver
        /// </summary>
        public DateTime? DtLocalizado { get; set; }
        /// <summary>
        /// Local onde o cadáver foi localizado
        /// </summary>
        public string Local { get; set; }
        /// <summary>
        /// Data aproximada da morte
        /// </summary>
        public DateTime? DtMorte { get; set; }
        /// <summary>
        /// Descrição de características assimétricas do cadáver
        /// </summary>
        public string Assimetria { get; set; }
        /// <summary>
        /// Descrição das tatuagens encontradas no cadáver
        /// </summary>
        public string Tatuagem { get; set; }
        /// <summary>
        /// Descrição de sinais naturais do cadáver
        /// </summary>
        public string Sinal { get; set; }
        /// <summary>
        /// Descrição sobre esmalte nas unhas do cadáver
        /// </summary>
        public string Esmalte { get; set; }
        /// <summary>
        /// Descrição de cirurgias encontradas no cadáver
        /// </summary>
        public string Cirurgia { get; set; }
        /// <summary>
        /// Descrição sobre próteses encontradas no cadáver
        /// </summary>
        public string Protese { get; set; }
        /// <summary>
        /// Informa se o cadáver foi identificado
        /// </summary>
        public bool? Identificado { get; set; }
        /// <summary>
        /// Informações adicionais sobre o cadáver
        /// </summary>
        public string Obs { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu a ficha
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão da ficha de cadáver ignorado
        /// </summary>
        public DateTime? DtIncluiu { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}