// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Instrumento causador da morte ou lesão
    /// </summary>
    public partial class TbInstrumento
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do instrumento causador da morte ou lesão
        /// </summary>
        public int CdInstrumento { get; set; }
        /// <summary>
        /// Nome do instrumento causador da morte ou lesão
        /// </summary>
        public string NmInstrumento { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}