// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Itens que compoem um termo de movimentação de bens patrimoniais (TMBP) para fora do IML
    /// </summary>
    public partial class TbItemTmbpExterno
    {
        /// <summary>
        /// Chave estrangeira na tabela tb_patrimonio. Código do bem patrimonial que compoe o TMBP EXTERNO
        /// </summary>
        public int CdPatrimonio { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_tmbp_externo. Código do TMBP externo ao qual o item pertence
        /// </summary>
        public int CdTmbp { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}