// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Laudos com visualização bloqueada por algum usuário
    /// </summary>
    public partial class TbLaudoBloqueado
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do laudo que deverá ser bloqueada a visualização
        /// </summary>
        public int CdLaudoBloqueado { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo com a visualização bloqueada
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Data do início do bloqueio da visualização do laudo
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que solicitou o bloqueio da visualização do laudo
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Descrição do motivo do bloqueio da visualização do laudo, Será exibido aos usuários que tentarem ver o laudo.
        /// </summary>
        public string Motivo { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        /// <summary>
        /// Data da exclusão do registro de bloqueio da visualização
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o registro de bloqueio de visualização
        /// </summary>
        public int? CdExcluidor { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}