// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Laudos cujos dados foram importados do sistema Millenium
    /// </summary>
    public partial class TbLaudoImportado
    {
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo cujos dados foram importados da ocorrência policial
        /// </summary>
        public int CdLaudo { get; set; }
        /// <summary>
        /// Data da importação dos dados da ocorrência para o laudo
        /// </summary>
        public DateTime DtImportacao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que fez a importação dos dados da ocorrência
        /// </summary>
        public int CdImportador { get; set; }
        /// <summary>
        /// Histórico da ocorrência policial
        /// </summary>
        public string HistoricoOcorrencia { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}