// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    ///  Laudos que o perito informou que foi coletado material para exame de laboratório
    /// </summary>
    public partial class TbLaudoColeta
    {
        /// <summary>
        /// Código do registro da coleta de material de um laudo
        /// </summary>
        public int CdColeta { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo para o qual foi coletado material para exame
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Data da inclusão do registro de que foi coletado material para exame
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que registrou a coleta de material
        /// </summary>
        public int? CdUsuario { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}