// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Alterações nas respostas dos quesitos dos laudos
    /// </summary>
    public partial class TbLogQuesito
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da alteração na resposta do quesito do laudo
        /// </summary>
        public int CdLogQuesito { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo cuja resposta do quesito foi alterada
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário (legista) que alterou a resposta do quesito
        /// </summary>
        public int? CdUsuario { get; set; }
        /// <summary>
        /// Data da alteração da resposta do quesito do laudo
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_quesito_laudo. Código do quesito que teve a resposta alterada
        /// </summary>
        public int? CdQuesitoLaudo { get; set; }
        /// <summary>
        /// Resposta do quesito antes da alteração
        /// </summary>
        public string RespostaAntiga { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}