// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Usuários que visualizaram as informações básicas do laudo (espelho) sem a parte da perícia médica
    /// </summary>
    public partial class TbLogEspelho
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da visualização do espelho do laudo pelo usuário
        /// </summary>
        public int CdLogEspelho { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo que foi visualizado o espelho
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que visualizou o espelho do laudo
        /// </summary>
        public int? CdUsuario { get; set; }
        /// <summary>
        /// Data da visualização do espelho do laudo pelo usuário
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Identificação do computador utilizado para visualizar o espelho do laudo
        /// </summary>
        public string Ip { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}