// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Registro das exclusões de fotos dos laudos
    /// </summary>
    public partial class TbLogFotoExcluida
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da exclusão de uma foto de um laudo
        /// </summary>
        public int CdLogFotoExcluida { get; set; }
        /// <summary>
        /// Data da exclusão da foto do laudo
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_foto. Código da foto que foi excluída
        /// </summary>
        public int? CdFoto { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu a foto do laudo
        /// </summary>
        public int? CdExcluidor { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}