// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Registro de visualização de gráficos (JPG) dos gráficos por usuários do SICOLA
    /// </summary>
    public partial class TbLogGrafico
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da visualização de um gráfico pelo usuário
        /// </summary>
        public int CdLogGrafico { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que visualizou o gráfico
        /// </summary>
        public int? CdUsuario { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo ao qual pertence o gráfico visualizado
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Data da visualização do gráfico pelo usuário
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Identificação do computador utilizado para visualizar o gráfico
        /// </summary>
        public string Ip { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}