// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Justificativa de usuários externos para visualizar laudos. Deixou de ser usado em 21/09/2009
    /// </summary>
    public partial class TbLogVisualizaJustifica
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da justificativa feita por um usuário para ver um laudo
        /// </summary>
        public int CdLogVisualizaJustifica { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo cujo usuário justificou a sua visualização
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que justificou a visualização de um laudo
        /// </summary>
        public int? CdUsuario { get; set; }
        /// <summary>
        /// Data da justificativa de visualização de um laudo
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Justificativa para visualizar um laudo
        /// </summary>
        public string Justificativa { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}