// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Visualizações dos documentos (laudos, relatório ou SVO)
    /// </summary>
    public partial class TbLogVisualiza
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da visualização de um laudo
        /// </summary>
        public int CdLogVisualiza { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo que foi visualizado
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que visualizou o laudo
        /// </summary>
        public int? CdUsuario { get; set; }
        /// <summary>
        /// Data da visualização do laudo pelo usuário
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Identificação do computador utilizado para visualizar o laudo
        /// </summary>
        public string Ip { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}