// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Motivos para intimação de um periciando. Este recurso não é utilizado no SICOLA.
    /// </summary>
    public partial class TbMotivoIntimacao
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do motivo para a intimação de um periciando
        /// </summary>
        public int CdMotivo { get; set; }
        /// <summary>
        /// Descrição do motivo para intimação de um periciando
        /// </summary>
        public string NmMotivo { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}