// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Tabela básica com os motivos do dano causado nas etiquetas fornecidas pela CGCV para a Central de Material e Vestígios do IML
    /// </summary>
    public partial class TbMotivoEtiqueta
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do motivo do dano na etiqueta
        /// </summary>
        public int CdMotivo { get; set; }
        /// <summary>
        /// Descrição do motivo que causou o dano na etiqueta fornecida pela CGCV
        /// </summary>
        public string NmMotivo { get; set; }
        /// <summary>
        /// Data da exclusão do registro de motivo de dano na etiqueta
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o motivo de dano na etiqueta
        /// </summary>
        public int? CdExcluidor { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}