// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Dicionário de nomes próprios para conferência ortográfica na qualificação do periciando do laudo
    /// </summary>
    public partial class TbNome
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do nome próprio
        /// </summary>
        public int CodNome { get; set; }
        /// <summary>
        /// Nome próprio registrado para conferência dos laudos
        /// </summary>
        public string NomePessoa { get; set; }
        /// <summary>
        /// Matrícula do usuário que incluiu o nome próprio
        /// </summary>
        public string Matricula { get; set; }
        /// <summary>
        /// Informa se o nome foi conferido por alguém e está correto
        /// </summary>
        public string Conferido { get; set; }
        /// <summary>
        /// Campo não utilizado
        /// </summary>
        public int? Qtde { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}