// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Controla a numeração dos termos de movimentação de bens patrimoniais EXTERNA ao IML
    /// </summary>
    public partial class TbNumeroTmbpExt
    {
        /// <summary>
        /// Chave primaria. Ano que se está controlando a numeração do TMPBE
        /// </summary>
        public int AnoTmbp { get; set; }
        /// <summary>
        /// Chave primaria. Último número de TMPBE utilizado no ano
        /// </summary>
        public int ValorTmbp { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}