// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Controle do último número de laudo de identificação necropapiloscópica utilizado pelo I.I. para identificar um cadáver
    /// </summary>
    public partial class TbNumeroIi
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do ultimo número utilizado
        /// </summary>
        public int CdNumeroIi { get; set; }
        /// <summary>
        /// Ano que se está controlando a numeração
        /// </summary>
        public int? Ano { get; set; }
        /// <summary>
        /// Último número utilizado pela necropapiloscopia no ano correspondente
        /// </summary>
        public int? Valor { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}