// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Usuários do sicola que estão online
    /// </summary>
    public partial class TbOnline
    {
        /// <summary>
        /// Chave primaria. Data do último acesso do usuário
        /// </summary>
        public DateTime DtAcesso { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que está online
        /// </summary>
        public int CdUsuario { get; set; }
        /// <summary>
        /// Nome da página que o usuário está acessando
        /// </summary>
        public string Pagina { get; set; }
        /// <summary>
        /// Identificação do computador de onde o usuário está acessando
        /// </summary>
        public string Ip { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}