// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Tabela não utilizada no SICOLA. 
    /// </summary>
    public partial class TbPalavra
    {
        /// <summary>
        /// Tabela não utilizada
        /// </summary>
        public int CodPalavra { get; set; }
        /// <summary>
        /// Tabela não utilizada
        /// </summary>
        public string Palavra { get; set; }
        /// <summary>
        /// Tabela não utilizada
        /// </summary>
        public string Conferida { get; set; }
        /// <summary>
        /// Tabela não utilizada
        /// </summary>
        public string Matricula { get; set; }
        /// <summary>
        /// Tabela não utilizada
        /// </summary>
        public int? Qtde { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}