// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Perícias indiretas realizadas no IML. As perícias indiretas não são feitas na pessoa, normalmente é feita em prontuários médicos.
    /// </summary>
    public partial class TbPe
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da perícia indireta
        /// </summary>
        public int CdPe { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro da perícia indireta
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão da perícia indireta
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o registro da perícia indireta
        /// </summary>
        public int? CdExcluidor { get; set; }
        /// <summary>
        /// Data da exclusão da perícia indireta
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        /// <summary>
        /// Número do protocolo da PCDF referente ao documento que originou a perícia indireta
        /// </summary>
        public int? NrProtocolo { get; set; }
        /// <summary>
        /// Número do ano do protocolo da PCDF referente ao documento que originou a perícia indireta
        /// </summary>
        public int? AnoProtocolo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_orgao. Código do órgão que originou o protocolo
        /// </summary>
        public int? CdOrgaoProtocolo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo vinculado à perícia indireta
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_hospital. Código do hospital onde está o prontuário médico. Deixou de ser usado em 2013
        /// </summary>
        public int? CdHospital { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_tp_documento. Código do tipo de documento que originou a perícia indireta
        /// </summary>
        public int? CdTpDoc { get; set; }
        /// <summary>
        /// Número do documento que originou a perícia indireta
        /// </summary>
        public string NrDoc { get; set; }
        /// <summary>
        /// Data do documento que originou a perícia indireta
        /// </summary>
        public DateTime? DtDoc { get; set; }
        /// <summary>
        /// Nome do periciando dono do prontuário objeto da perícia indireta
        /// </summary>
        public string NmPericiando { get; set; }
        /// <summary>
        /// Data do recebimento do documento que originou a perícia indireta
        /// </summary>
        public DateTime? DtRecebimento { get; set; }
        /// <summary>
        /// Data do encaminhamento da documentação para o legista
        /// </summary>
        public DateTime? DtEncaminhamento { get; set; }
        /// <summary>
        /// Data da devolução da documentação pelo legista
        /// </summary>
        public DateTime? DtDevolucao { get; set; }
        /// <summary>
        /// Anotações importantes sobre a perícia indireta
        /// </summary>
        public string Obs { get; set; }
        /// <summary>
        /// Informa se a perícia indireta deu origem a um novo laudo
        /// </summary>
        public bool? SemLaudo { get; set; }
        /// <summary>
        /// Nome do hospital onde está o prontuário médico
        /// </summary>
        public string NmHospital { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário responsável por fazer a perícia indireta (legista)
        /// </summary>
        public int? CdPerito { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}