// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Cadastro de agendamento de perícias cíveis solicitadas ao IML
    /// </summary>
    public partial class TbPericiaCivil
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do agendamento de uma perícia civil
        /// </summary>
        public int CdPericiaCivil { get; set; }
        /// <summary>
        /// Data da inclusão do agendamento da perícia
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o agendamento da perícia
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da exclusão do agendamento da perícia
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o agendamento da perícia
        /// </summary>
        public int? CdExcluidor { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do legista que irá realizar a perícia
        /// </summary>
        public int? CdPerito { get; set; }
        /// <summary>
        /// Data da perícia
        /// </summary>
        public DateTime? DtPericia { get; set; }
        /// <summary>
        /// Número do protocolo da PCDF que originou o pedido da perícia cívil
        /// </summary>
        public int? NrProtocolo { get; set; }
        /// <summary>
        /// Ano do protocolo da PCDF
        /// </summary>
        public int? AnoProtocolo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_orgao. Código do órgão do protocolo
        /// </summary>
        public int? CdOrgaoProtocolo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_tp_documento. Código do tipo de documento que solicitou a perícia
        /// </summary>
        public int? CdTpDocumento { get; set; }
        /// <summary>
        /// Número do documento que solicitou a perícia
        /// </summary>
        public int? NrDocumento { get; set; }
        /// <summary>
        /// Ano do documento que solicitou a perícia
        /// </summary>
        public int? AnoDocumento { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_orgao. Código do órgão emissor do documento que solicitou a perícia
        /// </summary>
        public int? CdOrgaoDocumento { get; set; }
        /// <summary>
        /// Nome do periciando que será examinado
        /// </summary>
        public string NmPericiando { get; set; }
        /// <summary>
        /// Informações complementares sobre a perícia civil agendada
        /// </summary>
        public string Obs { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}