// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Relação das possíveis permissões dadas aos usuários do SICOLA
    /// </summary>
    public partial class TbPermissao
    {
        /// <summary>
        /// Chave primaria autoincremental. Código da permissão dada ao usuário
        /// </summary>
        public int CdPermissao { get; set; }
        /// <summary>
        /// Descrição da permissão do usuário
        /// </summary>
        public string NmPermissao { get; set; }
        /// <summary>
        /// Sigla da permissão
        /// </summary>
        public string SiglaPermissao { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
        public int? Area { get; set; }
    }
}