// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Pertence de cadáver recolhido no IML pelo técnico de necrópsia
    /// </summary>
    public partial class TbPertence
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do pertence recolhido
        /// </summary>
        public int CdPertence { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cadaver. Código do cadáver dono do pertence
        /// </summary>
        public int? CdCadaver { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o pertence do cadáver
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão do pertence recolhido
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Hora da inclusão do pertence recolhido. Este campo deixou de ser usado em setembro de 2009.
        /// </summary>
        public DateTime? HrInclusao { get; set; }
        /// <summary>
        /// Data da entrega do pertence recolhido ao familiar responsável pelo cadáver
        /// </summary>
        public DateTime? DtEntrega { get; set; }
        /// <summary>
        /// Descrição do pertence que foi recolhido do cadáver
        /// </summary>
        public string DsPertence { get; set; }
        /// <summary>
        /// Nome do familiar que recebeu o pertence
        /// </summary>
        public string NmRecebedor { get; set; }
        /// <summary>
        /// Número do RG do familiar que recebeu o pertence
        /// </summary>
        public string RgRecebedor { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o pertence recolhido
        /// </summary>
        public int? Excluidor { get; set; }
        /// <summary>
        /// Data da exclusão do registro do pertence recolhido
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}