// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Pedido de prorrogação de prazo para conclusão do laudo. Pedido feito pelo legista. Deixou de ser usado em fevereiro de 2018 a pedido da diretora, Dra Cyntia, e passou a ser feito via ofício.
    /// </summary>
    public partial class TbProrrogacao
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do pedido de prorrogação de prazo de conclusão de laudo
        /// </summary>
        public int CdProrrogacao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo ao qual está solicitando a prorrogação de prazo de conclusão
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que solicitou a prorrogação de prazo
        /// </summary>
        public int? CdUsuario { get; set; }
        /// <summary>
        /// Data da solicitação de prorrogação de prazo
        /// </summary>
        public DateTime? DtPedido { get; set; }
        /// <summary>
        /// Motivo da solicitação de prorrogação de prazo para conclusão de laudo
        /// </summary>
        public string Motivo { get; set; }
        /// <summary>
        /// Data provável para o término do laudo
        /// </summary>
        public DateTime? DtTermino { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}