// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Agendamento de exames psicopatológicos de um paciente
    /// </summary>
    public partial class TbPscExame
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do agendamento de um exame psicopatológico
        /// </summary>
        public int CdExame { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_psc_paciente. Código do paciente que está sendo agendado
        /// </summary>
        public int? CdPaciente { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que está criando o agendamento do exame psicopatológico
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão do agendamento
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o agendamento do exame psicopatológico
        /// </summary>
        public int? CdExcluidor { get; set; }
        /// <summary>
        /// Data da exclusão do agendamento do exame psicopatológico
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        /// <summary>
        /// Data do exame agendado
        /// </summary>
        public DateTime? DtExame { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que fará o exame psicopatológico
        /// </summary>
        public int? CdPerito { get; set; }
        /// <summary>
        /// Informa se o periciando faltou ao exame agendado
        /// </summary>
        public bool? Faltou { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_tp_documento. Código do tipo de documento que solicitou o exame no periciando
        /// </summary>
        public int? CdTpDocumento { get; set; }
        /// <summary>
        /// Número do documento que solicitou o exame no periciando
        /// </summary>
        public string NrDocumento { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_orgao. Código do órgão emissor do documento que solicitou o exame
        /// </summary>
        public int? CdOrgaoDocumento { get; set; }
        /// <summary>
        /// Data do documento que solicitou o exame psicopatológico
        /// </summary>
        public DateTime? DtDocumento { get; set; }
        /// <summary>
        /// Data do recebimento, pelo IML, do documento que solicitou o exame psicopatológico
        /// </summary>
        public DateTime? DtRecebidoDoc { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo originado a partir do exame psicopatológico
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Data da devolução da documentação pelo servidor responsável pelo exame psicopatológico
        /// </summary>
        public DateTime? DtDevolvido { get; set; }
        /// <summary>
        /// Número do documento gerado para a devolução da documentação pelo IML
        /// </summary>
        public string DocDevolvido { get; set; }
        /// <summary>
        /// Número do protocolo da PCDF para a devolução da documentação
        /// </summary>
        public int? NrProtocolo { get; set; }
        /// <summary>
        /// Ano do protocolo da PCDF para a devolução da documentação
        /// </summary>
        public int? AnoProtocolo { get; set; }
        /// <summary>
        /// Tipo do exame realizado: 1 = psicológico e 2 = psiquiátrico
        /// </summary>
        public int? TipoExame { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}