// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Pedidos de exame radiológico. Este recurso não é utilizado desde 2009.
    /// </summary>
    public partial class TbRadiologico
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do pedido de exame radiológico feito pelo legista
        /// </summary>
        public int CdRadiologico { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo cujo exame radiológico foi solicitado
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Data da solicitação do exame radiológico
        /// </summary>
        public DateTime? DtSolicitacao { get; set; }
        /// <summary>
        /// Data do início do exame radiológico
        /// </summary>
        public DateTime? DtInicio { get; set; }
        /// <summary>
        /// Data do término do exame radiológico
        /// </summary>
        public DateTime? DtTermino { get; set; }
        /// <summary>
        /// Data do recebimento do resultado do exame radiológico pelo legista do laudo
        /// </summary>
        public DateTime? DtHomologacao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário (legista) que solicitou o exame radiológico
        /// </summary>
        public int? CdSolicitante { get; set; }
        /// <summary>
        /// Informa se o pedido de exame radiológico foi cancelado
        /// </summary>
        public bool? Cancelado { get; set; }
        /// <summary>
        /// Informações adicionais do legista para a radiologia
        /// </summary>
        public string Pedido { get; set; }
        /// <summary>
        /// Resultado do exame radiológico
        /// </summary>
        public string Resposta { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário da radiologia responsável pelo resultado
        /// </summary>
        public int? CdPeritoRadio { get; set; }
        /// <summary>
        /// Data do arquivamento do resultado pelo legista solicitante
        /// </summary>
        public DateTime? DtArquivado { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}