// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Pedidos de exames radiológicos cujos laudos foram aditados em virtude do resultado do exame. Este recurso não é utilizado desde 2009
    /// </summary>
    public partial class TbRadioAditado
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do pedido de exame radiológico cujo laudo foi aditado
        /// </summary>
        public int CdRadioAditado { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_radiologico. Código do pedido de exame radiológico cujo laudo foi aditado
        /// </summary>
        public int? CdRadiologico { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_aditamento. Código do aditamento do laudo
        /// </summary>
        public int? CdAditamento { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}