// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta tabela não é utilizada no SICOLA. Serviria para informar se um aditamento foi criado para alterar dados do periciando do laudo. Nunca foi implementado
    /// </summary>
    public partial class TbRetificacao
    {
        /// <summary>
        /// Esta tabela não é utilizada no SICOLA
        /// </summary>
        public int CdRetificacao { get; set; }
        /// <summary>
        /// Esta tabela não é utilizada no SICOLA
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Esta tabela não é utilizada no SICOLA
        /// </summary>
        public int CdAditamento { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}