// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Resposta do quesito do laudo
    /// </summary>
    public partial class TbRespostaQuesito
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da resposta do quesito de um laudo
        /// </summary>
        public int CdRespostaQuesito { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo cujo quesito está sendo respondido
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_quesito_laudo. Código do quesito que está sendo respondido
        /// </summary>
        public int? CdQuesitoLaudo { get; set; }
        /// <summary>
        /// Resposta do quesito do laudo
        /// </summary>
        public string Resposta { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}