// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Termo de responsabilidade pela retirada do corpo
    /// </summary>
    public partial class TbResponsavelCadaver
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do termo de responsabilidade pela retirada do corpo
        /// </summary>
        public int CdResponsavel { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo ao qual pertence o cadáver objeto do termo de responsabilidade
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Nome da pessoa que está se responsabilizando pela retirada do corpo para sepultamento
        /// </summary>
        public string NmResponsavel { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cidade. Código da cidade onde nasceu a pessoa responsável pela retirada do corpo
        /// </summary>
        public int? CdNaturalidade { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_estado. Código do estado onde se localiza a cidade onde nasceu o responsável pela retirada do corpo
        /// </summary>
        public int? CdUfNaturalidade { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_estado_civil. Código do estado civil da pessoa responsável pela retirada do corpo
        /// </summary>
        public int? CdEstadoCivil { get; set; }
        /// <summary>
        /// Nome do pai da pessoa responsável pela retirada do corpo do IML
        /// </summary>
        public string NmPai { get; set; }
        /// <summary>
        /// Nome da mãe da pessoa responsável pela retirada do corpo do IML
        /// </summary>
        public string NmMae { get; set; }
        /// <summary>
        /// Número do RG do responsável pela retirada do corpo
        /// </summary>
        public string Rg { get; set; }
        /// <summary>
        /// Órgão emissor do documento de identidade do responsável pela retirada do corpo
        /// </summary>
        public string Expedidor { get; set; }
        /// <summary>
        /// Endereço do responsável pela retirada do corpo
        /// </summary>
        public string Endereco { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cidade. Código da cidade do endereço do responsável pela retirada do corpo
        /// </summary>
        public int? CdCidadeEnd { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_estado. Código do estado da cidade do endereço do responsável pela retirada do corpo
        /// </summary>
        public int? CdUfEnd { get; set; }
        /// <summary>
        /// Data da inclusão do registro do termo de responsabilidade
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Hora da inclusão do registro do termo de responsabilidade
        /// </summary>
        public DateTime? HrInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o termo de responsabilidade
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Nome da primeira testemunha do termo de responsabilidade
        /// </summary>
        public string Testemunha1 { get; set; }
        /// <summary>
        /// Nome da segunda testemunha do termo de responsabilidade
        /// </summary>
        public string Testemunha2 { get; set; }
        /// <summary>
        /// Nome da terceira testemunha do termo de responsabilidade
        /// </summary>
        public string Testemunha3 { get; set; }
        /// <summary>
        /// Número do RG da primeira testemunha
        /// </summary>
        public string Rg1 { get; set; }
        /// <summary>
        /// Número do RG da segunda testemunha
        /// </summary>
        public string Rg2 { get; set; }
        /// <summary>
        /// Número do RG da terceira testemunha
        /// </summary>
        public string Rg3 { get; set; }
        /// <summary>
        /// Número do telefone da primeira testemunha
        /// </summary>
        public string Fone1 { get; set; }
        /// <summary>
        /// Número do telefone da segunda testemunha
        /// </summary>
        public string Fone2 { get; set; }
        /// <summary>
        /// Número do telefone da terceira testemunha
        /// </summary>
        public string Fone3 { get; set; }
        /// <summary>
        /// Endereço da primeira testemunha
        /// </summary>
        public string Endereco1 { get; set; }
        /// <summary>
        /// Endereço da segunda testemunha
        /// </summary>
        public string Endereco2 { get; set; }
        /// <summary>
        /// Endereço da terceira testemunha
        /// </summary>
        public string Endereco3 { get; set; }
        /// <summary>
        /// Data da assinatura do termo de responsabilidade
        /// </summary>
        public DateTime? DtTermo { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}