// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Registro de raio X realizado em um cadáver
    /// </summary>
    public partial class TbRx
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro de raio X realizado em um cadáver
        /// </summary>
        public int CdRx { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela cd_cadaver. Código do cadáver onde foi feito o Raio X
        /// </summary>
        public int? CdCadaver { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro de raio X realizado
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Quantidade de filmes de raio x utilizados
        /// </summary>
        public int? QtdeFilmes { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que realizou o procedimento de Raio X no cadáver
        /// </summary>
        public int? CdFezRx { get; set; }
        /// <summary>
        /// Data da inclusão do registro
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Quantidade de projetis encontrados no corpo
        /// </summary>
        public int? QtdeProjetis { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}