// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Livro de controle de saídas do rabecão
    /// </summary>
    public partial class TbSaidaRabecao
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro da saída do rabecão
        /// </summary>
        public int CdSaidaRabecao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo referente à remoção (é preenchido depois do retorno do rabecão)
        /// </summary>
        public int? CdLaudo { get; set; }
        /// <summary>
        /// Data da inclusão da saída do rabecão
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro da saída do rabecão
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_orgao. Código do órgão (DP) que solicitou a remoção
        /// </summary>
        public int? CdOrgao { get; set; }
        /// <summary>
        /// Número da guia de remoção de cadáver
        /// </summary>
        public int? NrGuia { get; set; }
        /// <summary>
        /// Ano da guia de remoção de cadáver
        /// </summary>
        public int? AnoGuia { get; set; }
        /// <summary>
        /// Número da ocorrência policial relacionada com a remoção
        /// </summary>
        public int? NrOcorrencia { get; set; }
        /// <summary>
        /// Ano da ocorrência policial relacionada com a remoção
        /// </summary>
        public int? AnoOcorrencia { get; set; }
        /// <summary>
        /// Data da solicitação da remoção pela CIADE
        /// </summary>
        public DateTime? DtPedido { get; set; }
        /// <summary>
        /// Nome do operador de rádio da CIADE
        /// </summary>
        public string OperadorCiade { get; set; }
        /// <summary>
        /// Local onde será feita a remoção
        /// </summary>
        public string Local { get; set; }
        /// <summary>
        /// Nome (provável) do cadáver que será removido ao IML
        /// </summary>
        public string Periciando { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_sexo. Código do sexo (provável) do cadáver
        /// </summary>
        public int? CdSexo { get; set; }
        /// <summary>
        /// Causa (provável) da morte
        /// </summary>
        public string Causa { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário motorista do rabecão
        /// </summary>
        public int? CdMotorista { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_viatura. Código da viatura (rabecão) utilizada na remoção
        /// </summary>
        public int? CdViatura { get; set; }
        /// <summary>
        /// Data da saída do rabecão
        /// </summary>
        public DateTime? DtSaida { get; set; }
        /// <summary>
        /// Data da chegada do rabecão (retorno)
        /// </summary>
        public DateTime? DtChegada { get; set; }
        /// <summary>
        /// Nome do operador de rádio no IML
        /// </summary>
        public string OperadorIml { get; set; }
        /// <summary>
        /// Informações adicionais sobre a remoção
        /// </summary>
        public string Obs { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o registro
        /// </summary>
        public int? CdExcluidor { get; set; }
        /// <summary>
        /// Data que o IC comunicou o término da perícia criminal do local
        /// </summary>
        public DateTime? DtIc { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}