// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Relacionamento entre a tabela de órgãos (tb_orgao_lotacao) e a tabela de seções (tb_secao_lotacao), para indicar ao SICOLA a qual órgão pertencem as seções.
    /// </summary>
    public partial class TbSecaoOrgao
    {
        /// <summary>
        /// Chave primaria. Chave estrangeira na tabela tb_orgao_lotacao. Código do órgão ao qual pertence a seção
        /// </summary>
        public int CdOrgaoLotacao { get; set; }
        /// <summary>
        /// Chave primaria. Chave estrangeira na tabela tb_secao_lotacao. Código da seção que pertence ao órgão
        /// </summary>
        public int CdSecaoLotacao { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}