// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Serviço de verificação de óbito. Essa tabela deixou de ser utilizada em abril de 2017, os cadáveres do SVO passaram a ser controlados como CONTROLE DO SVO na própria tabela de laudos (tb_laudo).
    /// </summary>
    public partial class TbSvo
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do cadáver do SVO
        /// </summary>
        public int CdSvo { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro do SVO
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão do registro do SVO
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que excluiu o registro do SVO
        /// </summary>
        public int? CdExcluidor { get; set; }
        /// <summary>
        /// Data da exclusão do registro 
        /// </summary>
        public DateTime? DtExclusao { get; set; }
        /// <summary>
        /// Data da entrada do cadáver do SVO no IML
        /// </summary>
        public DateTime? DtEntrada { get; set; }
        /// <summary>
        /// Número da ocorrência policial relacionada ao cadáver
        /// </summary>
        public int? NrOcorrencia { get; set; }
        /// <summary>
        /// Ano da ocorrência policial relacionada ao cadáver
        /// </summary>
        public int? AnoOcorrencia { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_orgao. Código do órgão (DP) emissor da ocorrência
        /// </summary>
        public int? CdOrgaoOcorrencia { get; set; }
        /// <summary>
        /// Número da guia de remoção referente ao cadáver
        /// </summary>
        public int? NrGuia { get; set; }
        /// <summary>
        /// Ano da guia de remoção referente ao cadáver
        /// </summary>
        public int? AnoGuia { get; set; }
        /// <summary>
        /// Número do memorando que encaminhou o cadáver
        /// </summary>
        public int? NrMemo { get; set; }
        /// <summary>
        /// Ano do memorando que encaminhou o cadáver
        /// </summary>
        public int? AnoMemo { get; set; }
        /// <summary>
        /// Nome do cadáver
        /// </summary>
        public string NmCadaver { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário (médico do SVO) responsável pelo cadáver
        /// </summary>
        public int? CdPerito { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que recebeu a guia de remoção de cadáver
        /// </summary>
        public int? CdRecebeuGuia { get; set; }
        /// <summary>
        /// Data do recebimento da guia de remoção de cadáver
        /// </summary>
        public DateTime? DtRecebeuGuia { get; set; }
        /// <summary>
        /// Data da saída do corpo do IML
        /// </summary>
        public DateTime? DtSaida { get; set; }
        /// <summary>
        /// Informações adicionais sobre o cadáver do SVO
        /// </summary>
        public string Obs { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}