// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Tipo de exame laboratorial
    /// </summary>
    public partial class TbTpExame
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do tipo de exame laboratorial
        /// </summary>
        public int CdTpExame { get; set; }
        /// <summary>
        /// Código único que identifica o tipo de exame laboratorial
        /// </summary>
        public string Codificacao { get; set; }
        /// <summary>
        /// Descrição do tipo de exame laboratorial
        /// </summary>
        public string NmTpExame { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}