// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta tabela não é utilizada no SICOLA
    /// </summary>
    public partial class TbTpDocDa
    {
        /// <summary>
        /// Esta tabela não é utilizada
        /// </summary>
        public int CdTpDocDa { get; set; }
        /// <summary>
        /// Esta tabela não é utilizada
        /// </summary>
        public string Descricao { get; set; }
        /// <summary>
        /// Esta tabela não é utilizada
        /// </summary>
        public bool? Excluido { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}