// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Cadastro de usuários do SICOLA. Registra todos os usuários, independente da função exercida.
    /// </summary>
    public partial class TbUsuario
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do usuário do SICOLA
        /// </summary>
        public int CdUsuario { get; set; }
        /// <summary>
        /// Nome completo do usuário
        /// </summary>
        public string NmUsuario { get; set; }
        /// <summary>
        /// Chave estrangeira tb_orgao_lotacao. Código do órgão de lotação do usuário
        /// </summary>
        public int? CdOrgaoLotacao { get; set; }
        /// <summary>
        /// Chave estrangeira tb_secao_lotacao. Código da seção de lotação do usuário
        /// </summary>
        public int? CdSecao { get; set; }
        /// <summary>
        /// Nome abreviado ou apelido do usuário
        /// </summary>
        public string Guerra { get; set; }
        /// <summary>
        /// Pronome de tratamento para o usuário
        /// </summary>
        public string Tratamento { get; set; }
        /// <summary>
        /// Campo utilizado para saber se o usuário recebeu um determinado aviso 
        /// </summary>
        public bool? Avisado { get; set; }
        /// <summary>
        /// Número do telefone celular do usuário
        /// </summary>
        public string Celular { get; set; }
        /// <summary>
        /// Número do CPF do usuário
        /// </summary>
        public string Cpf { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_conselho. Código do registro do conselho de classe do usuário, se o usuário faz laudo
        /// </summary>
        public int? CdConselho { get; set; }
        /// <summary>
        /// Número do conselho de classe do usuário, se o usuário faz laudo
        /// </summary>
        public string NrConselho { get; set; }
        /// <summary>
        /// Nome do arquivo de configuração do site, escolhido como preferencial pelo usuário
        /// </summary>
        public string Css { get; set; }
        /// <summary>
        /// Data em que a senha do usuário vai expirar
        /// </summary>
        public DateTime? ExpiraSenha { get; set; }
        /// <summary>
        /// Nome da figura escolhida pelo usuário para ser exibida no topo de todas as páginas
        /// </summary>
        public string Figtop { get; set; }
        /// <summary>
        /// Matrícula do usuário
        /// </summary>
        public string Matricula { get; set; }
        /// <summary>
        /// Informações adicionais sobre o usuário
        /// </summary>
        public string Obs { get; set; }
        /// <summary>
        /// Pergunta informada pelo usuário para que ele possa recuperar sua própria senha esquecida
        /// </summary>
        public string Pergunta { get; set; }
        /// <summary>
        /// Resposta para a pergunta informada pelo usuário para recuperar sua senha
        /// </summary>
        public string Resposta { get; set; }
        /// <summary>
        /// Permissões concedidas ao usuário para utilizar dentro do SICOLA
        /// </summary>
        public string Permissoes { get; set; }
        /// <summary>
        /// Número do RG do usuário
        /// </summary>
        public string Rg { get; set; }
        /// <summary>
        /// Senha criptografada do usuário
        /// </summary>
        public string Senha { get; set; }
        /// <summary>
        /// Data do último acesso do usuário
        /// </summary>
        public DateTime? UltimoAcesso { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        /// <summary>
        /// Data de nascimento do usuário
        /// </summary>
        public DateTime? DtNascimento { get; set; }
        /// <summary>
        /// Endereço do usuário
        /// </summary>
        public string Endereco { get; set; }
        /// <summary>
        /// Bairro do endereço do usuário
        /// </summary>
        public string Bairro { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cidade. Código da cidade do endereço do usuário
        /// </summary>
        public int? CdCidade { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_estado. Código do estado da cidade do endereço do usuário
        /// </summary>
        public int? CdEstado { get; set; }
        /// <summary>
        /// Número do telefone residencial do usuário
        /// </summary>
        public string FoneRes { get; set; }
        /// <summary>
        /// Número do telefone celular do usuário
        /// </summary>
        public string FoneCel { get; set; }
        /// <summary>
        /// Número de outro telefone do usuário
        /// </summary>
        public string FoneOutro { get; set; }
        /// <summary>
        /// Código do banco onde o usuário recebe o pagamento
        /// </summary>
        public string CdBanco { get; set; }
        /// <summary>
        /// Número da agencia onde o usuário recebe o pagamento
        /// </summary>
        public string Agencia { get; set; }
        /// <summary>
        /// Número da conta corrente do usuário
        /// </summary>
        public string ContaCorrente { get; set; }
        /// <summary>
        /// Grau de instrução do usuário: 1-Fundamental  2-Médio 3-Superior
        /// </summary>
        public int? GrauInstrucao { get; set; }
        /// <summary>
        /// Curso superior do usuário
        /// </summary>
        public string Curso { get; set; }
        /// <summary>
        /// Especialidade médica do usuário, se for médico legista
        /// </summary>
        public string Especialidade { get; set; }
        /// <summary>
        /// Grupo sanguíneo do usuário
        /// </summary>
        public string TipoSangue { get; set; }
        /// <summary>
        /// Fator RH do usuário (sangue)
        /// </summary>
        public int? FatorRh { get; set; }
        /// <summary>
        /// Código do SIAPE do usuário
        /// </summary>
        public string Siape { get; set; }
        /// <summary>
        /// Endereço de email do usuário
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Número do título de eleitor do usuário
        /// </summary>
        public string Titulo { get; set; }
        /// <summary>
        /// Zona de votação do usuário
        /// </summary>
        public string Zona { get; set; }
        /// <summary>
        /// Nome do cargo para o qual o usuário foi nomeado AD HOC (quem faz relatórios)
        /// </summary>
        public string NmCargoAdHoc { get; set; }
        /// <summary>
        /// Campo não utilizado no SICOLA
        /// </summary>
        public int? CdCargo { get; set; }
        public DateTime? DtCadastro { get; set; }
        public int? Cadastrador { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
        public string MatriculaBkp { get; set; }

        public virtual TbOrgaoLotacao CdOrgaoLotacaoNavigation { get; set; }
        public virtual TbSecaoLotacao CdSecaoNavigation { get; set; }
    }
}