// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Usuário que auxiliou na veste do cadáver
    /// </summary>
    public partial class TbVeste
    {
        /// <summary>
        /// Chave primaria autoincremental. Código do registro do usuário auxiliar da veste
        /// </summary>
        public int CdVeste { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_cadaver. Código do cadáver que foi vestido pelo usuário
        /// </summary>
        public int? CdCadaver { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que incluiu o registro do auxílio na veste
        /// </summary>
        public int? CdIncluidor { get; set; }
        /// <summary>
        /// Data da inclusão do registro de auxílio na veste do cadáver
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Chave estrangeira na tabela tb_usuario. Código do usuário que auxiliou na veste do cadáver
        /// </summary>
        public int? CdVestiu { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}