// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Relação de laudos de lesão corporal de mulheres vítimas de violência doméstica (para estatística)
    /// </summary>
    public partial class TbViolenciaDomestica
    {
        /// <summary>
        /// Chave estrangeira na tabela tb_laudo. Código do laudo da vítima de violência doméstica
        /// </summary>
        public int CdLaudo { get; set; }
        /// <summary>
        /// Data da inclusão do registro de violência doméstica
        /// </summary>
        public DateTime? DtInclusao { get; set; }
        /// <summary>
        /// Informa se o registro foi excluído
        /// </summary>
        public bool? Excluido { get; set; }
        /// <summary>
        /// Escolaridade da mulher vítima da violência doméstica
        /// </summary>
        public string Escolaridade { get; set; }
        /// <summary>
        /// Informa se a mulher está gestante
        /// </summary>
        public string Gestante { get; set; }
        /// <summary>
        /// Data do acontecimento da violência doméstica
        /// </summary>
        public DateTime? DtFato { get; set; }
        /// <summary>
        /// Quantidade de vezes que o episódio se repetiu
        /// </summary>
        public int? NrEpisodio { get; set; }
        /// <summary>
        /// Quantidade de filhos da vítima
        /// </summary>
        public int? Filhos { get; set; }
        /// <summary>
        /// Informa se algum dos filhos reside com a vítima
        /// </summary>
        public string FilhoReside { get; set; }
        public string Abortou { get; set; }
        public string Deficiente { get; set; }
        public string TpViolencia { get; set; }
        public string Autor { get; set; }
        public string AutorReside { get; set; }
        public string VioDom { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}