// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta tabela não foi criada no IML, não sei qual a sua utilização.
    /// </summary>
    public partial class TdSolicitacaoIml
    {
        /// <summary>
        /// Chave primaria
        /// </summary>
        public int CodSolicitacao { get; set; }
        public int CodUnidadePolicialSolicitante { get; set; }
        public DateTime DataHoraSolicitacao { get; set; }
        public short CodTipoDocumentoSolicitante { get; set; }
        public int NrDocumentoSolicitante { get; set; }
        public long CodSeqDocumentosDiversos { get; set; }
        public string CodMatriculaSolicitante { get; set; }
        public int AnoOcorrencia { get; set; }
        public int CodUnidadePolicialOcorrencia { get; set; }
        public int NrOcorrencia { get; set; }
        public int AditamentoOcorrencia { get; set; }
        public int CodPessoaOcorrencia { get; set; }
        public string NomePessoaOcorrencia { get; set; }
        public string NomeMaePessoaOcorrencia { get; set; }
        public DateTime DataNascPessoaOcorrencia { get; set; }
        public DateTime? DataHoraDeslocamento { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
    }
}