// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class TempPositivoToxic
    {
        public string Laudo { get; set; }
        public DateTime? DtSolicitacao { get; set; }
        public string NmSubstancia { get; set; }
        public string NmResposta { get; set; }
    }
}