// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class TempHomicidioFeminino20062011
    {
        public string NmPericiando { get; set; }
        public string NmOrgaoOcorrencia { get; set; }
        public int? NrOcorrencia { get; set; }
        public int? AnoOcorrencia { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
    }
}