// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwAditamentosPorPeriodo
    {
        public int? NrLaudo { get; set; }
        public DateTime? DtInclusao { get; set; }
        public bool? Administrativo { get; set; }
        public DateTime? DtHomologado { get; set; }
    }
}