// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Aditamentos de laudos e relatórios
    /// </summary>
    public partial class VwAditamento
    {
        public int CdAditamento { get; set; }
        public int? CdLaudo { get; set; }
        public DateTime? DtInclusao { get; set; }
        public DateTime? HrInclusao { get; set; }
        public int? CdIncluidor { get; set; }
        public DateTime? DtAssinatura { get; set; }
        public DateTime? HrAssinatura { get; set; }
        public int? CdPerito1 { get; set; }
        public int? CdPerito2 { get; set; }
        public bool? Administrativo { get; set; }
        public int? CdHomologador { get; set; }
        public DateTime? DtHomologado { get; set; }
        public DateTime? HrHomologado { get; set; }
        public int? CdArquivador { get; set; }
        public DateTime? DtArquivado { get; set; }
        public DateTime? HrArquivado { get; set; }
        public int? CdDestinatario { get; set; }
        public string Texto { get; set; }
        public int? QtFotos { get; set; }
        public bool? Cancelado { get; set; }
        public string NmPericiando { get; set; }
        public string NmTpLaudo { get; set; }
        public string NmPerito1 { get; set; }
        public string NmPerito2 { get; set; }
        public string NmDestinatario { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public string NrConselho1 { get; set; }
        public string SiglaConselho1 { get; set; }
        public string NrConselho2 { get; set; }
        public string SiglaConselho2 { get; set; }
        public string NmHomologador { get; set; }
        public string NmArquivador { get; set; }
        public string NmIncluidor { get; set; }
        public string MtIncluidor { get; set; }
        public int? NrProtocolo { get; set; }
        public int? AnoProtocolo { get; set; }
        public string MatriculaPerito1 { get; set; }
        public string MatriculaPerito2 { get; set; }
        public string NmDocumento { get; set; }
        public string NrDocumento { get; set; }
        public string NmOrgao { get; set; }
    }
}