// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Anexos de laudos. Deixou de ser usado em junho de 2007.
    /// </summary>
    public partial class VwAnexo
    {
        public int CdAnexo { get; set; }
        public int CdLaudo { get; set; }
        public int? CdHomologador { get; set; }
        public int? CdArquivador { get; set; }
        public DateTime? DtHomologado { get; set; }
        public DateTime? HrHomologado { get; set; }
        public DateTime? DtArquivado { get; set; }
        public DateTime? HrArquivado { get; set; }
        public int? NrFolhas { get; set; }
        public string Obs { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public string NmPerito1 { get; set; }
        public string NmHomologador { get; set; }
    }
}