// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Avisos da página inicial do SICOLA que devem ser exibidas (estão dentro do prazo).
    /// </summary>
    public partial class VwAvisoDa
    {
        public int CdAviso { get; set; }
        public DateTime? DtInicio { get; set; }
        public DateTime? DtFinal { get; set; }
        public string Titulo { get; set; }
        public string Aviso { get; set; }
        public bool? Excluido { get; set; }
        public bool? PgInicial { get; set; }
        public bool? Popup { get; set; }
        public int? TamanhoFonte { get; set; }
        public string CorFonte { get; set; }
        public string CorFundo { get; set; }
    }
}