// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Usuários do SICOLA assinalados como chefe de seção
    /// </summary>
    public partial class VwChefeSecao
    {
        public int CdOrgaoLotacao { get; set; }
        public int CdSecaoLotacao { get; set; }
        public int CdUsuario { get; set; }
        public string NmOrgaoLotacao { get; set; }
        public string NmSecaoLotacao { get; set; }
        public string NmUsuario { get; set; }
        public bool? Excluido { get; set; }
    }
}