// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Memorandos de encaminhamento de contraprova à CGCV. Deixou de ser usado em 17/02/11
    /// </summary>
    public partial class VwContraprova
    {
        public int CdContraprova { get; set; }
        public DateTime DtIncluido { get; set; }
        public string Memo { get; set; }
        public int? NrProtocolo { get; set; }
        public int? AnoProtocolo { get; set; }
        public DateTime? DtAssinatura { get; set; }
        public string Texto { get; set; }
        public bool? Excluido { get; set; }
        public bool? Expr1 { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public int? NrProtocolo2 { get; set; }
        public int? AnoProtocolo2 { get; set; }
    }
}