// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Cópia de laudo fornecida para delegacia. Deixou de ser usado em 13/09/2016
    /// </summary>
    public partial class VwCopia
    {
        public int CdCopia { get; set; }
        public int? CdLaudo { get; set; }
        public bool? Adt { get; set; }
        public DateTime? DtInclusao { get; set; }
        public DateTime? DtEntrega { get; set; }
        public int? CdIncluiu { get; set; }
        public int? CdEntregou { get; set; }
        public string Recebeu { get; set; }
        public int? CdDestinatario { get; set; }
        public string Obs { get; set; }
        public string NmDestinatario { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public string NmTpLaudo { get; set; }
        public string NmDestinatarioCopia { get; set; }
        public string NmIncluiu { get; set; }
        public string NmEntregou { get; set; }
    }
}