// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Controle de documentos recebidos e encaminhados pela SAPE. Recurso nunca utilizado pela seção.
    /// </summary>
    public partial class VwDocs
    {
        public int CdDocs { get; set; }
        public int? CdTpDocumento { get; set; }
        public string NrDocumento { get; set; }
        public int? CdOrgao { get; set; }
        public string NmTipo { get; set; }
        public int? NrProtocolo { get; set; }
        public int? AnoProtocolo { get; set; }
        public int? CdServidor { get; set; }
        public DateTime? DtEntrega { get; set; }
        public DateTime? DtInclusao { get; set; }
        public int? CdIncluidor { get; set; }
        public DateTime? DtRetorno { get; set; }
        public DateTime? DtPrazo { get; set; }
        public string Obs { get; set; }
        public bool? Excluido { get; set; }
        public int? CdExcluidor { get; set; }
        public string NmOrgao { get; set; }
        public string NmServidor { get; set; }
        public string NmExcluidor { get; set; }
        public string NmDocumento { get; set; }
    }
}