// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Escala de deslocamento emergencial dos legistas
    /// </summary>
    public partial class VwEscala
    {
        public int CdEscala { get; set; }
        public int CdUsuario { get; set; }
        public DateTime DtEscala { get; set; }
        public string TpEscala { get; set; }
        public string NmUsuario { get; set; }
        public string Guerra { get; set; }
        public string Matricula { get; set; }
    }
}