// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwExamesLaboratoriais
    {
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public int? NrOcorrencia { get; set; }
        public int? AnoOcorrencia { get; set; }
        public string Solicitante { get; set; }
        public DateTime? DtLaudo { get; set; }
        public string NmPericiando { get; set; }
        public string NmSexo { get; set; }
        public DateTime? DtNascimento { get; set; }
        public bool? Cancelado { get; set; }
        public string CausaMedica { get; set; }
        public string CausaJuridica { get; set; }
        public string Instrumento { get; set; }
        public int? CdLaudo { get; set; }
        public string NmSuspeita { get; set; }
        public decimal? Quantitativo { get; set; }
        public string NmMetodo { get; set; }
        public string NmResposta { get; set; }
    }
}