// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Guias de recolhimento, traslado e conservação de cadáver emitidas pelo IML para as funerárias
    /// </summary>
    public partial class VwGrtcc
    {
        public int CdGrtcc { get; set; }
        public int? CdCadaver { get; set; }
        public int? CdIncluidor { get; set; }
        public DateTime? DtInclusao { get; set; }
        public string Ip { get; set; }
        public string NmIncluidor { get; set; }
        public string NmOrgaoLotacao { get; set; }
    }
}