// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Laudos dos últimos 30 dias. Essa listagem é utilizada no sicola para procurar outros laudos de um mesmo periciando no período de 30 dias.
    /// </summary>
    public partial class VwHomonimo
    {
        public int CdLaudo { get; set; }
        public DateTime? DtLaudo { get; set; }
        public string NmPericiando { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public string NmMae { get; set; }
    }
}