// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Usuários que homologam laudos. É a listagem de todos os usuário que possuem a permissão H1 (entrar na área da homologação)
    /// </summary>
    public partial class VwHomologador
    {
        public int CdUsuario { get; set; }
        public string NmUsuario { get; set; }
    }
}