// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Ficha com características do cadáver classificado como ignorado (sem identificação) pela seção de necrópsia
    /// </summary>
    public partial class VwIgnoradoFicha
    {
        public int CdIgnoradoFicha { get; set; }
        public int? CdLaudo { get; set; }
        public short? Peso { get; set; }
        public short? Estatura { get; set; }
        public int? CdCorPele { get; set; }
        public int? CdCorCabelo { get; set; }
        public int? CdTpCabelo { get; set; }
        public string Veste { get; set; }
        public string Adereco { get; set; }
        public int? CdSexo { get; set; }
        public short? Idade { get; set; }
        public short? NrCalcado { get; set; }
        public string Cicatriz { get; set; }
        public string Fratura { get; set; }
        public string Dente { get; set; }
        public DateTime? DtLocalizado { get; set; }
        public string Local { get; set; }
        public DateTime? DtMorte { get; set; }
        public string Assimetria { get; set; }
        public string Tatuagem { get; set; }
        public string Sinal { get; set; }
        public string Esmalte { get; set; }
        public string Cirurgia { get; set; }
        public string Protese { get; set; }
        public bool? Identificado { get; set; }
        public string Obs { get; set; }
        public int? CdIncluidor { get; set; }
        public DateTime? DtIncluiu { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public string NmPericiando { get; set; }
        public string NmIncluidor { get; set; }
        public string NmCorPele { get; set; }
        public string NmTpCabelo { get; set; }
        public string NmCorCabelo { get; set; }
        public string NmSexo { get; set; }
        public bool? Excluido { get; set; }
    }
}