// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Laudos classificados como ignorados (periciandos sem identificação)
    /// </summary>
    public partial class VwIgnorado
    {
        public string NmPericiando { get; set; }
        public DateTime? DtLaudo { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public int? CdLaudo { get; set; }
        public int CdIgnorado { get; set; }
        public bool? Excluido { get; set; }
        public bool? Cancelado { get; set; }
    }
}