// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwInformatica
    {
        public string Tombamento { get; set; }
        public string Descrição { get; set; }
        public string NrSerie { get; set; }
        public int? Tp { get; set; }
        public DateTime? DtBaixa { get; set; }
        public int? CdOrgaoLotacao { get; set; }
        public string NmSecaoLotacao { get; set; }
    }
}