// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    public partial class VwInstrumentoCausaDaMorte
    {
        public int? CdLaudo { get; set; }
        public DateTime? DtInclusao { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public DateTime? DtLaudo { get; set; }
        public string NmCausaJurPerito { get; set; }
        public string NmCausaJurDp { get; set; }
        public string NmCausaMedica { get; set; }
        public string NmInstrumento { get; set; }
        public string NmSexo { get; set; }
        public string NmTpLaudo { get; set; }
        public int? CodOrgaoOcorrencia { get; set; }
    }
}