// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Códigos de todos os usuários que incluiram laudos no mês atual
    /// </summary>
    public partial class VwIncluidorMes
    {
        public int? CdIncluidor { get; set; }
    }
}