// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Visualizações dos documentos (laudos, relatório ou SVO)
    /// </summary>
    public partial class VwLogVisualiza
    {
        public DateTime? DtInclusao { get; set; }
        public string NmUsuario { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public int? CdLaudo { get; set; }
        public string Ip { get; set; }
        public string NmOrgaoLotacao { get; set; }
        public string Matricula { get; set; }
        public int? CdUsuario { get; set; }
        public int? Expr1 { get; set; }
    }
}