// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Justificativa de usuários externos para visualizar laudos. Deixou de ser usado em 21/09/2009
    /// </summary>
    public partial class VwLogVisualizaJustifica
    {
        public string Matricula { get; set; }
        public string NmUsuario { get; set; }
        public DateTime? DtInclusao { get; set; }
        public string Justificativa { get; set; }
        public int? CdLaudo { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
    }
}