// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Usuários que visualizaram apenas as fotos do laudo
    /// </summary>
    public partial class VwLogImagem
    {
        public string NmUsuario { get; set; }
        public int CdLaudo { get; set; }
        public DateTime DtInclusao { get; set; }
        public string Ip { get; set; }
    }
}