// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Material de consumo e a seção que o utiliza. Informa para qual seção um material de consumo pode ser distribuido
    /// </summary>
    public partial class VwMaterialSecao
    {
        public string DescMaterial { get; set; }
        public int CodMaterial { get; set; }
        public int? CodOrgao { get; set; }
        public int? EstoqueMinimo { get; set; }
        public int? EstoqueMaximo { get; set; }
        public int? EstoqueAtual { get; set; }
        public string UnidadeMedida { get; set; }
        public string Excluido { get; set; }
        public int? CodSecao { get; set; }
        public string NmSecao { get; set; }
    }
}