// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Mensagens enviadas e recebidas entre usuários do sistema
    /// </summary>
    public partial class VwMensagem
    {
        public int CdMensagem { get; set; }
        public int? CdRemetente { get; set; }
        public int? CdDestinatario { get; set; }
        public DateTime? DtMensagem { get; set; }
        public string Mensagem { get; set; }
        public DateTime? DtRecebimento { get; set; }
        public bool? ExcluidoR { get; set; }
        public bool? ExcluidoD { get; set; }
        public string Assunto { get; set; }
        public long? IdTrilhaAuditoria { get; set; }
        public string NmRemetente { get; set; }
        public string NmDestinatario { get; set; }
    }
}