// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada pelo SICOLA
    /// </summary>
    public partial class VwMortesNaturais
    {
        public int? CdCausaJurPerito { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public DateTime? DtInclusao { get; set; }
    }
}