// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Informações adicionais (observações) incluídas nos laudos.
    /// </summary>
    public partial class VwObsLaudo
    {
        public int CdObsLaudo { get; set; }
        public string Texto { get; set; }
        public int? CdLaudo { get; set; }
        public bool? Imprime { get; set; }
        public int? CdUsuario { get; set; }
        public DateTime? DtObs { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? CdExcluidor { get; set; }
        public string NmUsuario { get; set; }
    }
}