// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Usuários do sicola que estão online
    /// </summary>
    public partial class VwOnline
    {
        public DateTime DtAcesso { get; set; }
        public string NmUsuario { get; set; }
        public string NmOrgaoLotacao { get; set; }
        public string Pagina { get; set; }
    }
}