// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Cadastro de agendamento de perícias cíveis solicitadas ao IML
    /// </summary>
    public partial class VwPericiaCivil
    {
        public int CdPericiaCivil { get; set; }
        public DateTime? DtInclusao { get; set; }
        public int? CdIncluidor { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? CdExcluidor { get; set; }
        public int? CdPerito { get; set; }
        public DateTime? DtPericia { get; set; }
        public int? NrProtocolo { get; set; }
        public int? AnoProtocolo { get; set; }
        public int? CdOrgaoProtocolo { get; set; }
        public int? CdTpDocumento { get; set; }
        public int? NrDocumento { get; set; }
        public int? AnoDocumento { get; set; }
        public int? CdOrgaoDocumento { get; set; }
        public string NmPericiando { get; set; }
        public string Obs { get; set; }
        public string NmPerito { get; set; }
        public string NmOrgaoProtocolo { get; set; }
        public string NmOrgaoDocumento { get; set; }
    }
}