// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA e não foi criada no IML
    /// </summary>
    public partial class VwPeUltimoLaudo
    {
        public int? CdLaudo { get; set; }
        public int? CdPerito1 { get; set; }
        public DateTime? DtLaudo { get; set; }
    }
}