// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Laudos da seção de psicopatologia (laudos psiquiátricos e psicológicos)
    /// </summary>
    public partial class VwPsicopatologia
    {
        public string NmOrgao { get; set; }
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public int CdLaudo { get; set; }
        public string NmTpLaudo { get; set; }
        public bool? Cancelado { get; set; }
        public DateTime? DtArquivado { get; set; }
        public DateTime? DtLaudo { get; set; }
        public int? CdOrgao { get; set; }
        public string NmPericiando { get; set; }
    }
}