// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Servidor da seção de necrópsia que auxiliou na remoção do cadáver
    /// </summary>
    public partial class VwRemocao
    {
        public int CdRemocao { get; set; }
        public int? CdCadaver { get; set; }
        public int? CdIncluidor { get; set; }
        public DateTime? DtInclusao { get; set; }
        public DateTime? HrInclusao { get; set; }
        public int? CdRemoveu { get; set; }
        public string NmRemoveu { get; set; }
        public string NmIncluidor { get; set; }
    }
}