// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Solicitacao de retenção ou aviso de homologação de um laudo
    /// </summary>
    public partial class VwRetencao
    {
        public int CdRetencao { get; set; }
        public int CdLaudo { get; set; }
        public int CdReteve { get; set; }
        public DateTime DtRetencao { get; set; }
        public int TipoDoc { get; set; }
        public string Motivo { get; set; }
        public bool Excluido { get; set; }
        public int CdLiberou { get; set; }
        public int Quando { get; set; }
        public string NmReteve { get; set; }
        public string NmLiberou { get; set; }
    }
}