// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Seção (parte) dos laudos onde o legista digita as informações da perícia realizada
    /// </summary>
    public partial class VwSecaoLaudo
    {
        public int CdSecaoLaudo { get; set; }
        public int? CdTpLaudo { get; set; }
        public string NmSecaoLaudo { get; set; }
        public string TextoPadrao { get; set; }
        public int? Ordem { get; set; }
        public bool? Excluido { get; set; }
        public string NmTpLaudo { get; set; }
    }
}