// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Relacionamento entre a tabela de órgãos (tb_orgao_lotacao) e a tabela de seções (tb_secao_lotacao), para indicar ao SICOLA a qual órgão pertencem as seções.
    /// </summary>
    public partial class VwSecaoOrgao
    {
        public string NmOrgaoLotacao { get; set; }
        public string NmSecaoLotacao { get; set; }
        public int CdOrgaoLotacao { get; set; }
        public int CdSecaoLotacao { get; set; }
    }
}