// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwSugestaoComentario
    {
        public string Comentario { get; set; }
        public DateTime? DtInclusao { get; set; }
        public int? CdIncluidor { get; set; }
        public int? CdSugestao { get; set; }
        public int CdSugestaoComentario { get; set; }
        public string NmIncluidor { get; set; }
        public bool? Excluido { get; set; }
    }
}