// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwTempUltimoAcessoUsuario
    {
        public string Matricula { get; set; }
        public string NmUsuario { get; set; }
        public string NmOrgaoLotacao { get; set; }
        public string Permissoes { get; set; }
        public string UltimoAcesso { get; set; }
    }
}