// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwTempCyntiaMortesELaborat
    {
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public DateTime? DtLaudo { get; set; }
        public string NmCausaJuridica { get; set; }
        public int? CdLaudo { get; set; }
        public int? CdToxicologico { get; set; }
        public string NmSubstancia { get; set; }
        public string NmResposta { get; set; }
        public string CausaJurDp { get; set; }
        public string NmCausaMedica { get; set; }
    }
}