// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwTempConcatenaLaudoSql
    {
        public string NmPerito2 { get; set; }
        public string Laudo { get; set; }
        public DateTime? DtLaudo { get; set; }
        public string NmTpLaudo { get; set; }
        public string Documento { get; set; }
        public DateTime? DtDocumento { get; set; }
        public string Protocolo { get; set; }
    }
}