// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwTempCautelares
    {
        public DateTime? DtLaudo { get; set; }
        public string NmTpLaudo { get; set; }
        public bool? Cancelado { get; set; }
        public string Horario { get; set; }
        public string NmTpExameLc { get; set; }
    }
}