// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwTempAcidenteTransito
    {
        public DateTime? DtLaudo { get; set; }
        public string Laudo { get; set; }
        public int? Idade { get; set; }
        public string NmSexo { get; set; }
        public string Ocorrencia { get; set; }
        public string NmOrgaoOcorrencia { get; set; }
    }
}