// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwTempTemp
    {
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public string NmTpLaudo { get; set; }
        public DateTime? DtNascimento { get; set; }
        public DateTime? DtLaudo { get; set; }
        public string NmSecaoLaudo { get; set; }
        public string TextoSecao { get; set; }
        public string NmSexo { get; set; }
        public string NmCorPele { get; set; }
        public int? NrOcorrencia { get; set; }
        public int? AnoOcorrencia { get; set; }
        public string NmOrgao { get; set; }
        public int? CdLaudo { get; set; }
        public string NmPericiando { get; set; }
    }
}