// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwTempMorteSubitaMenorUmAno
    {
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public DateTime? DtLaudo { get; set; }
        public DateTime? DtNascimento { get; set; }
        public bool? Cancelado { get; set; }
        public int? Idade { get; set; }
    }
}