// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Termo de movimentação de bens patrimoniais externo (para fora do IML
    /// </summary>
    public partial class VwTmbpExterno
    {
        public DateTime? DtMovimento { get; set; }
        public int? CdSecaoOrigem { get; set; }
        public int? CdOrgaoDestino { get; set; }
        public int? ValorTmbp { get; set; }
        public int? AnoTmbp { get; set; }
        public string ChefeOrigem { get; set; }
        public int CdPatrimonio { get; set; }
        public int CdTmbp { get; set; }
        public string NmPatrimonio { get; set; }
        public string Origem { get; set; }
        public string Destino { get; set; }
        public string Tombamento { get; set; }
        public string Estado { get; set; }
    }
}