// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Esta consulta não é utilizada no SICOLA
    /// </summary>
    public partial class VwToxicologicoCyntiaTemp
    {
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public DateTime? DtNascimento { get; set; }
        public DateTime? DtLaudo { get; set; }
        public string Naturalidade { get; set; }
        public string NmNacionalidade { get; set; }
        public string NmOrgao { get; set; }
        public string NmCorPele { get; set; }
        public string NmEstadoCivil { get; set; }
        public string NmCidade { get; set; }
        public string NmEstado { get; set; }
        public string NmSexo { get; set; }
        public string NmSubstancia { get; set; }
        public string NmResposta { get; set; }
        public string NmCausaMedica { get; set; }
        public string NmCausaJurDp { get; set; }
        public string Historico { get; set; }
    }
}