// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Relacionamento entre o pedido de exame e a substância analisada. É onde o laboratório informa o resultado para cada substância separadamente.
    /// </summary>
    public partial class VwToxicologicoSubstancia
    {
        public string NmSubstancia { get; set; }
        public int? CdSuspeita { get; set; }
        public string NmSuspeita { get; set; }
        public int CdToxicSubst { get; set; }
        public int? CdToxicologico { get; set; }
        public int? CdSubstancia { get; set; }
        public int? CdRespostaSubstancia { get; set; }
        public decimal? Quantitativo { get; set; }
        public string NmMetodo { get; set; }
    }
}