// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PCDF.Servico.Sicola.API.Data.Data.Sicola
{
    /// <summary>
    /// Exames laboratoriais iniciados e não concluídos (baseado nas datas de início e conclusão)
    /// </summary>
    public partial class VwToxicologicoEdicao
    {
        public int? NrLaudo { get; set; }
        public int? AnoLaudo { get; set; }
        public int CdToxicologico { get; set; }
        public string NmSubstancia { get; set; }
        public string NmEspecifica { get; set; }
        public DateTime? DtInicio { get; set; }
        public string NrLaudoTox { get; set; }
        public int? CdLaudo { get; set; }
        public string NmTpLaudo { get; set; }
        public int? Prioridade { get; set; }
        public bool? Cancelado { get; set; }
        public DateTime? DtPeritoTox { get; set; }
        public int? CdPeritoTox { get; set; }
        public string TpExame { get; set; }
        public string NmPeritoTox { get; set; }
        public string Texto { get; set; }
        public string TpExameLaudo { get; set; }
    }
}